### ISSUE TITLE
[Suggest]Localized translation

### ISSUE THREAD

**Issue by 1677883418** [korcankaraokcu/PINCE#101]
Hello, I am from China. 
I want to contribute to the localization of "Pince". As a price, I can be added to the list of contributors.
If you agree, please reply me and we will do it.

**Comment by korcankaraokcu** [comment]
Unfortunately, label texts are hardcoded as for now, I'll notify you if that changes, thank you for the suggestion.

I won't close the issue for future use, have a good day.

**Comment by Domefemia** [comment]
> Hello, I am from China. I want to contribute to the localization of "Pince". As a price, I can be added to the list of contributors. If you agree, please reply me and we will do it.

Hey dude right now there is a work being done for localizing the app, I have already done something first korcankaraokcu need to accept my pull request and the translation can be done.

**Comment by korcankaraokcu** [comment]
This has been implemented. Check [CONTRIBUTING.md](https://github.com/korcankaraokcu/PINCE/blob/master/CONTRIBUTING.md#translation) for instructions. Also, I haven't updated the author list in years, github's own contributors list make more sense to look at
