### ISSUE TITLE
Searching for array of bytes does not guarantee searching in read/execute-only segments.

### ISSUE THREAD

**Issue by eLeCtrOssSnake** [korcankaraokcu/PINCE#107]
If you find any assembly instruction that you would like to get address of by pattern. If you try searching for it, apparently it won't yield any results, even if you copy bytes directly by inspecting the memory section.
On the other hand, when performing similar search for array of bytes for something in data section, pince correctly finds the data.

**Comment by korcankaraokcu** [comment]
Implemented scan scope option with https://github.com/korcankaraokcu/PINCE/commit/c00489995bc826759e5d611d02ddd63166d09554. Pull the latest changes and tell me if it works for you

**Comment by korcankaraokcu** [comment]
This feature has been integrated, closing the issue

**Comment by korcankaraokcu** [comment]
There are two modes of "Full" option now, Read+Write searches the all RW sections, Full searches for everything

**Comment by eLeCtrOssSnake** [comment]
No way! We can finally do proper AoB scans.

**Comment by korcankaraokcu** [comment]
Apparently there was one more bug about this feature, it has been fixed with the newest patch -> 14b1e041c109b840fac2e7a59ef73ed69561f930

**Comment by pollev** [comment]
Whoohoo! my feature was added!

**Comment by korcankaraokcu** [comment]
@pollev Indeed! Thanks for your contribution, it was much needed
