### ISSUE TITLE
pince-examine-expression causes game to become "not responding"

### ISSUE THREAD

**Issue by WorldTeacher** [korcankaraokcu/PINCE#109]
I was testing PINCE with Huniepop 2, since it causes Huniepop 1's process to stop, though I might have figured out why...
I was testing some vales to see if everything worked when the terminal I started PINCE with started showing these lines 
![image](https://user-images.githubusercontent.com/41587052/142859877-f93f9bd7-1004-4bd2-a9b2-388d5b215e88.png)
 PINCE itself is still working fine, only the game becomes like this:
![image](https://user-images.githubusercontent.com/41587052/142860050-85e63d09-3c9e-4ecd-90c3-487be9f239c0.png)

I am running the game using Lutris with the GOG installer and my OS is Manjaro Gnome running on a Surface Pro 5

**Comment by korcankaraokcu** [comment]
That command converts gdb expressions to values, it's used to update the table, nothing to worry about. If the process stops whenever you continue, [try this](https://github.com/korcankaraokcu/PINCE/wiki/Init-files)

**Comment by WorldTeacher** [comment]
Thanks for the fast reply, I'll give this a go in a bit.
I tried starting and connecting PINCE to HuniePop 1, but the process still gets stopped:
![image](https://user-images.githubusercontent.com/41587052/142878910-0bede6c1-ab49-40de-b90b-56135afbf625.png)
the game freezes every time the "UPDATED MEMORYVIEW" happens, if I close PINCE, the game waits for a second or so and resumes working as usual.
Any ideas?
The game is running through Proton 6.3-7

**Comment by korcankaraokcu** [comment]
What happens when you continue the game? Default hotkey is F3

**Comment by WorldTeacher** [comment]
I had to press F3 a few times, after that the game works for a bit this is the cli output:
![image](https://user-images.githubusercontent.com/41587052/142881250-d423c244-7082-4114-b9d4-ede6ab1691d0.png)
but after repeating the F3 workaround for a bit results in PINCE going back to the pince-examine-expression, and whenever I spam F3 to get the game working again, it just starts the pince-examine again

**Comment by korcankaraokcu** [comment]
Post the full log

**Comment by WorldTeacher** [comment]
this is all I can see in /dev7shm/PINCE-connection/
![image](https://user-images.githubusercontent.com/41587052/142885199-8c397f7f-e323-471e-8a24-60917dbf132f.png)
are there any other log locations?

**Comment by korcankaraokcu** [comment]
Sorry, I meant the console log of PINCE. Like the previous logs you have posted, but the entire thing.

**Comment by WorldTeacher** [comment]
here you go: https://pastebin.com/UZQKy4wc
do excuse that the pince-examine cut off some stuff at the beginning, should I start it again and make a new log?

**Comment by korcankaraokcu** [comment]
`~"17 \"HuniePop.x86_64\" received signal SIGPWR, Power fail/restart.\n"`
This is the problem. Try ignoring the signal, you can check [here ](https://github.com/korcankaraokcu/PINCE/wiki/Init-files)how to do it. Replace `SIGNAME` with `SIGPWR`

**Comment by WorldTeacher** [comment]
I added the code but all it causes the game to perma-freeze after I stared the stopped service using F3
Even trying to manually stop and start the service did nothing.
Latest log: https://pastebin.com/0LQN7XHh

**Comment by korcankaraokcu** [comment]
SIGINT is causing this now. It's a bit risky but try ignoring all of the signals: `handle all nopass`

**Comment by WorldTeacher** [comment]
So, I tried using "all" and the game wouldn't even let me enter the saved game
New log: https://pastebin.com/yikS4Zsc

**Comment by korcankaraokcu** [comment]
I honestly have got no idea, I don't own the game. Maybe try disabling only the SIGINT and SIGPWR?

**Comment by WorldTeacher** [comment]
I have tried using only  SIGINT and SIGPWR, and after a value search, it froze.

I have now tried using CheatEngine and ceserver and apart from some visual glitches it works fine, so I'll guess I'll use the for now, but I'll do some more testing to see if I can make it work.

**Comment by korcankaraokcu** [comment]
Settings menu now offers an option to ignore those signals, please try using the debug menu within settings. The new menu uses `nostop noprint` instead of `nopass`, maybe it can help

**Comment by WorldTeacher** [comment]
I'll give it a go on the weekend, thanks for letting me know

**Comment by korcankaraokcu** [comment]
How did it go for you? Just creating some notifications to remind, you can take your time

**Comment by WorldTeacher** [comment]
Sorry for the really late reply. I got busy with work and some personal stuff and completely forgot about it...

I installed Huniepop 2 and pince (using the aur package) and tried to execute pince, but got the following error:
 `python3: can't open file '/home/user/PINCE.py': [Errno 2] No such file or directory`

trying it with a git clone from the repo results in this error:
```
Traceback (most recent call last):
  File "/home/alexander/PINCE/PINCE.py", line 33, in <module>
    from libpince.libscanmem.scanmem import Scanmem
ModuleNotFoundError: No module named 'libpince.libscanmem'
```
even though the folder for libpince is present. The folder for scanmem is present as well and has a bunch of .c files in it

**Comment by korcankaraokcu** [comment]
Delete the pince folder and do a clean install. You need to clone the repository recursively as stated in the readme

**Comment by WorldTeacher** [comment]
I did that after a restart, and everything worked now. Thanks ^^

**Comment by korcankaraokcu** [comment]
Thanks for letting me know, I'm closing the issue then. Have a nice day!
