### ISSUE TITLE
ARM64 capabilities

### ISSUE THREAD

**Issue by FloDoc** [korcankaraokcu/PINCE#110]
Greetings! 

Great app! I was attempting to use it for a new GDB module bundled with the newest version of Atmosphere on the switch. But I've been noticing it doesn't want to play nice with ARM64. Would it be possible to have gdb_multiarch implemented? Or have some libs added from the switch SDK? I'd jump into the code and have a look myself, but I am not super familiar with Python.

**Comment by korcankaraokcu** [comment]
Neither ARM or switch is included on the roadmap. It's not the current priority, sorry about that. Maybe after 1.0 release

**Comment by FloDoc** [comment]
Thanks for the response! Figured it wouldn't hurt to ask. Again, nice work on the app!
