### ISSUE TITLE
I CAN NOT RUN PINCE

### ISSUE THREAD

**Issue by FxmlesXD** [korcankaraokcu/PINCE#111]
sh PINCE.sh
[sudo] cloversss 的密码：

(PINCE.py:1539): Gtk-WARNING **: 10:39:10.868: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()
/home/cloversss/PINCE/libpince/libscanmem/misc.py:24: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
QStandardPaths: runtime directory '/run/user/1000' is not owned by UID 0, but a directory permissions 0700 owned by UID 1000 GID 1000
Detached from the process with PID:-1
Last command: set logging off
^done
0.0013473033905029297
Last command: set logging file /dev/shm/PINCE-connection/-1/gdb_log.txt
=cmd-param-changed,param="logging file",value="/dev/shm/PINCE-connection/-1/gdb_log.txt"
^done
0.0006613731384277344
Last command: source /home/cloversss/.config/PINCE/PINCE_USER_FILES/gdbinit
^done
0.000644683837890625
Last command: handle SIGSEGV stop print
^done
0.0009517669677734375
Last command: set logging off
^done
0.0009047985076904297
Last command: set logging file /dev/shm/PINCE-connection/-1/gdb_log.txt
^done
0.0007500648498535156
Traceback (most recent call last):
  File "/home/cloversss/PINCE/PINCE.py", line 5261, in <module>
    window = MainForm()
  File "/home/cloversss/PINCE/PINCE.py", line 375, in __init__
    self.memory_view_window = MemoryViewWindowForm(self)
  File "/home/cloversss/PINCE/PINCE.py", line 2239, in __init__
    self.initialize_disassemble_view()
  File "/home/cloversss/PINCE/PINCE.py", line 2283, in initialize_disassemble_view
    GuiUtils.center_scroll_bar(self.verticalScrollBar_Disassemble)
  File "/home/cloversss/PINCE/libpince/GuiUtils.py", line 77, in center_scroll_bar
    QScrollBar.setValue((maximum + minimum) / 2)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

**Comment by FxmlesXD** [comment]
i use XFCE4,archlinux

**Comment by TsumiHokiro** [comment]
Second here.
KDE(X11), archlinux.
The second time today a python APP has failed me today (Bottles just failed me but managed to fix it.)

**Comment by FxmlesXD** [comment]
> Second here. KDE(X11), archlinux. The second time today a python APP has failed me today (Bottles just failed me but managed to fix it.)

if we use old version python ,can it fix

**Comment by TsumiHokiro** [comment]
Not sure, I ran into this issue https://github.com/bottlesdevs/Bottles/issues/768
At first, Pince didn't find "pygdbmi" so I ran the same solution as suggested over there which solved said problem.
I guess I could try downgrading to 3.10.0 since I just check that.

**Comment by TsumiHokiro** [comment]
Just did it, no luck.

**Comment by FxmlesXD** [comment]
> Wait, just reinstalled. Let me downgrade the whole kit.

i downgrading to 3.10.0 just now but it doesn't work , what about u

**Comment by TsumiHokiro** [comment]
Downgraded to 3.9.0, just made it worse.
I'll await further news.

**Comment by FxmlesXD** [comment]
> Downgraded to 3.9.0, just made it worse. Complaining about PyQt5, and I don't even know which version of pyqt I had, so I won't venture back there. I'll await further news.

i googled setValue(),it is a function of pyqt,so im downgrading pyqt

**Comment by FxmlesXD** [comment]
OK it doesn't work.

**Comment by korcankaraokcu** [comment]
https://github.com/korcankaraokcu/PINCE/commit/ecd8d5d92214592d47d46f16112d000c7834fab6 should fix your issue, update PINCE by running `git pull`

**Comment by FxmlesXD** [comment]
it work.
