### ISSUE TITLE
doas support

### ISSUE THREAD

**Issue by SArpnt** [korcankaraokcu/PINCE#112]
i prefer to use doas instead of sudo for better security, but since pince tries to use `sudo -E` (likely more but this is the only error i can see), pince doesn't work with doas, even when sudo is symlinked to doas

it would be nice if sudo wasn't required

**Comment by AdverseMiller** [comment]
You could probably alias "sudo -E" to doas in your .zshrc or .bashrc or something like that, not sure if it would when the program is issuing the command and not the shell

**Comment by korcankaraokcu** [comment]
Currently it's not necessary to swap sudo with something else as majority of the supported systems still use sudo over its alternatives. You'll have to come up with a local solution since it's your preference, sorry about that
