### ISSUE TITLE
New freeze option

### ISSUE THREAD

**Issue by rejedai** [korcankaraokcu/PINCE#113]
It would be extremely useful to have the function of freezing the value only when decreasing or increasing.

For example, we have a variable with a value of 20, if the program tries to decrease the value, it does not change, but when increasing everything works as it should.

**Comment by rejedai** [comment]
Well, I found how it works. 

Everything works with such a code, but I suck in GUI and will not be able to do PR, maybe it will help someone.

Place this at top **`PINCE.py`**:
```Python
class FreezeType(Enum):
    DEFAULT = 0
    INCREMENT = 1
    DECREMENT = 2
```

And this is instead of the `MainForm.freeze(self)` function:
```Python
def freeze(self, freeze_type=FreezeType.INCREMENT):
    while (FreezeStop == 0 and Exiting == 0):
        sleep(FreezeInterval / 1000)
        for x in FreezeVars:
            current_val = str(GDB_Engine.read_memory(x, FreezeVars[x][0]))
            if (freeze_type == FreezeType.INCREMENT and int(current_val) > int(FreezeVars[x][1])) or \
                    (freeze_type == FreezeType.DECREMENT and int(current_val) < int(FreezeVars[x][1])):
                FreezeVars[x][1] = current_val
            GDB_Engine.write_memory(x, FreezeVars[x][0], FreezeVars[x][1])
```

**Comment by rejedai** [comment]
My code needs to be improved. I think that when adding to `FreezeVars`, need to specify the type of freezing. Then need to replace the check with `FreezeVars[x][3]`, where `3` is the identifier of the type of freezing.

**Comment by rejedai** [comment]
And in the UI, you can use QComboBox with the parameters None, All, Dec, Inc, at least that's how I see it.

**Comment by korcankaraokcu** [comment]
This is a very useful feature, thanks for the suggestion. I'm currently fixing some scan related issues, this feature will be implemented eventually

**Comment by korcankaraokcu** [comment]
This feature has been implemented, closing the issue
Your code helped me btw, thanks for the insight. I had to refactor some stuff tho, check the last 4 patches for details

**Comment by MayeulC** [comment]
As a new user, I had trouble figuring what the options meant.

I suggest using "Increasing only" and "Decreasing only".

**Comment by korcankaraokcu** [comment]
I don't think it's necessary, fine as it is

**Comment by MayeulC** [comment]
My issue was: does "freeze decrease" mean that it can't decrease anymore? Or that it can only decrease.

**Comment by korcankaraokcu** [comment]
The freeze menu reads "Freeze->Decremental" meaning that the entry can only decrease. It's the opposite for "Incremental"

They even have colors to remove any confusion

**Comment by MayeulC** [comment]
I agree the colors helped me a bit. "Freeze -> Decremental" has the same issue: I first read this as freeze decremental operations.

Maybe it's just me, mind you. I thought that was unclear. Maybe adding a tooltip would clear the confusion.
I also dislike that I need to first toggle the freeze checkbox individually before having the "Freeze" option in the context menu. That makes it tedious to freeze larger memory arrays.

**Comment by korcankaraokcu** [comment]
You can select multiple entries and use the assigned hotkey to toggle the records, current hotkey is space
