### ISSUE TITLE
In uninstall section "/dev/shm/PINCE-connection/-1/gdb_log.txt" not mentioned 

### ISSUE THREAD

**Issue by MasterChenSensei** [korcankaraokcu/PINCE#114]
I didn't find any mention about "/dev/shm/PINCE-connection/-1/gdb_log.txt" in the "uninstall" section, and I guess it's no biggie, but thought it was worth bringing up.

**Comment by korcankaraokcu** [comment]
Shared memory files are temporary, no need to worry about them. That file path is used to communicate with gdb. I didn't include them in the uninstall section since they were temporary anyway
