### ISSUE TITLE
Crash when opening a new dialog

### ISSUE THREAD

**Issue by Offpics** [korcankaraokcu/PINCE#116]
Whenever I try to open a new dialog like, e.g. "Open Cheat Table", PINCE crashes and prints this output to the console:
```
/PINCE.py:1066: Warning: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-fallback-icon-theme'
  file_paths = QFileDialog.getOpenFileNames(self, "Open PCT file(s)", pct_file_path,
```

OS: EndeavourOS/Arch
DE: Gnome
Windowing System: Wayland with xorg-wayland

@cagriulas @TsarFox

**Comment by Offpics** [comment]
For anyone wondering, I've been able to fix it by installing qt5ct and launching it. Maybe worth mentioning this in the README.md?

**Comment by korcankaraokcu** [comment]
> Maybe worth mentioning this in the README.md

Yeah, definitely

Closing this issue since a fix was found

**Comment by jaredballou** [comment]
NB: When running qt5ct I got an error that I needed to change my environment variable QT_QPA_PLATFORMTHEME from gtk2 to qt5ct. Making that change resolved the issue for me.

**Comment by korcankaraokcu** [comment]
This crash seems to be specific to gnome, thank you for sharing your wisdom @jaredballou. Your solution works just fine
