### ISSUE TITLE
Getting SIGUSR1 signal

### ISSUE THREAD

**Issue by y5r43l** [korcankaraokcu/PINCE#120]
As soon as I attach the proccess it stops.

The console output shows:

`=thread-created,id="68",group-id="i1"
~"[New LWP 10940]\n"
*running,thread-id="68"
~"\nThread "
~"68 \"theHunterCotW_F\" received signal SIGUSR1, User defined signal 1.\n"
~"[Switching to LWP 10940]\n"
~"0x00007f5ddef3ea9d in ?? ()\n"
*stopped,reason="signal-received",signal-name="SIGUSR1",signal-meaning="User defined signal 1",frame={addr="0x00007f5ddef3ea9d",func="??",args=[],arch="i386:x86-64"},thread-id="68",stopped-threads="all",core="10"
~"[Switching to thread 68 (LWP 10940)]\n"
~"#0  0x00007f5ddef3ea9d in ?? ()\n"
=thread-selected,id="68",frame={level="0",addr="0x00007f5ddef3ea9d",func="??",args=[],arch="i386:x86-64"}
`
Tried appending `handle SIGUSR1 nopass` to gdbinit file with no success.

What can I do to solve this?

OS: Arch Linux
Game: theHunter: Call of the Wild (Steam)
Proton version: 7.0-1

**Comment by Bloodiko** [comment]
It's not `nopass` 
But `handle SIGUSR1 nostop` instead. 

Oh and take a note on the all caps signal name. 
Else it won't work.

**Comment by y5r43l** [comment]
Hi, thanks a lot for the quick answer.
It somehow worked, now I got another error: `Killed by signal 11.`
 
Sorry if I shouldn't post it in this issue.

**Comment by Bloodiko** [comment]
Signal 11 is SIGSEGV. Meaning read or write at an invalid or unauthorized memory address. 
Head over to the Discord in the On-The-Field channel, this is most likely not an issue of Pince - Either a scanmem issue, or your game. ( Or not an issue at all, since scanmem can still contain Addresses which got "Free"d by the program, thus you cannot access them anymore to read. which will kill your next search in return.  ) 
Tough this part is more than my knowledge at this point so i will keep myself out of this from here on.

**Comment by y5r43l** [comment]
Once again I'd like to thank you for the answer.

I'll go to Discord and if I get the problem solved I'll close this issue with the solution.

Cheers!

**Comment by korcankaraokcu** [comment]
Segfault is a known issue, it's occasionally caused by libscanmem

As for SIGUSR1, you can now choose to ignore it without having to modify init files, related patch: https://github.com/korcankaraokcu/PINCE/commit/9aeaa26a6b62336c827cee4dca41c80a0bc24279

**Comment by y5r43l** [comment]
As a workaround I found that pausing the proccess with F1 key before scanning for a value prevents PINCE from crashing with error code 11. After the scan finishes just resume with F3 key.
Thanks!

**Comment by korcankaraokcu** [comment]
That's interesting, thanks for letting us know
