### ISSUE TITLE
Fedora support?

### ISSUE THREAD

**Issue by pointydev** [korcankaraokcu/PINCE#122]
Hey there,

I'd love to see this packaged for Fedora, as it is a very capable piece of software. Distribution could be made easier using Copr (Fedora's user repository); there's a [publishing guide](https://docs.fedoraproject.org/en-US/quick-docs/publish-rpm-on-copr/) and [full user docs](https://docs.pagure.org/copr.copr/user_documentation.html) that have more information.

Also, I had to `dnf install libtool intltool readline-devel` to get `install_pince.sh` to complete correctly on my system, as they are not present by default.

Thanks,
Elliott

**Comment by korcankaraokcu** [comment]
I'm not a Fedora user myself but anyone who's willing to create such package is welcomed as a maintainer, leaving this issue open for this sake

**Comment by korcankaraokcu** [comment]
The installation script is now updated for Fedora as well. Fedora also has been added to supported systems. I'm still leaving this issue open tho, since there isn't a dedicated package right now

**Comment by korcankaraokcu** [comment]
On a second thought, Fedora is already being supported and tested on. Maybe packaging should have its own issue for clarity. We already have a Flatpak issue for universal packaging anyway. Closing as it's completed
