### ISSUE TITLE
Error executing PINCE.SH - Linux Mint 20.3 x86_64

### ISSUE THREAD

**Issue by RahRah80** [korcankaraokcu/PINCE#130]
Hello.
I got this error running...

Traceback (most recent call last):
  File "PINCE.py", line 31, in <module>
    from libpince import GuiUtils, SysUtils, GDB_Engine, type_defs
  File "/home/rah-rah/Games/cheat/pince/libpince/GuiUtils.py", line 24, in <module>
    from . import SysUtils, type_defs, common_regexes
  File "/home/rah-rah/Games/cheat/pince/libpince/SysUtils.py", line 32, in <module>
    from pygdbmi import gdbmiparser
ModuleNotFoundError: No module named 'pygdbmi'

Thank you.

**Comment by brkzlr** [comment]
As the error states, you're missing the pygdbmi dependency module.
If you're on Arch Linux and installed it through AUR, please check #126, otherwise try to do a git pull and run the install pince script

**Comment by RahRah80** [comment]
Hi brkzlr.

I'm new to git, how can i do it.
I ran git pull on terminal and don't know where to find a file .git

ran ./install_gdb.sh and got

make[2]: Leaving directory '/home/rah-rah/Games/cheat/pince/gdb_pince/gdb-10.2/gdbserver'
make[1]: Leaving directory '/home/rah-rah/Games/cheat/pince/gdb_pince/gdb-10.2'
make: *** [Makefile:854: all] Error 2
Failed to install GDB, restart the installation process

Thank you.

**Comment by korcankaraokcu** [comment]
As the readme says, `install_gdb` is used for situations where system gdb isn't available, it's unrelated to a usual installation workflow. Follow the installing tab of readme [here](https://github.com/korcankaraokcu/PINCE#installing)

**Comment by RahRah80** [comment]
Hi.

I read the page before downloading the source code, it was a wild stab in the dark... still printed out error.

A "desperate" act when you can't solve the problem.......

**Comment by RahRah80** [comment]
Problem solved by **`pip install pygdbmi`** on the terminal.
Got another error... another issue
