### ISSUE TITLE
Error running "from libpince.libscanmem.scanmem import Scanmem"

### ISSUE THREAD

**Issue by RahRah80** [korcankaraokcu/PINCE#131]
Hello.
```

Traceback (most recent call last):
  File "PINCE.py", line 32, in <module>
    from libpince.libscanmem.scanmem import Scanmem
ModuleNotFoundError: No module named 'libpince.libscanmem'
```

Scanmem is installed, gameconqueror as well and working right.

**Comment by korcankaraokcu** [comment]
Pince installs scanmem locally and uses it as a submodule. It's not affected by the system GC or scanmem. Make sure that you follow the install instructions thoroughly

**Comment by RahRah80** [comment]
> Pince installs scanmem locally and uses it as a submodule. It's not affected by the system GC or scanmem. Make sure that you follow the install instructions thoroughly

I compiled it and "install it" and GC was removed... strange

**Comment by korcankaraokcu** [comment]
It's compiled locally but apparently installed in `/usr`, my memory failed me for this one. I'll be fixing it soon. Does pince work for you right now tho? It has the most importance

**Comment by RahRah80** [comment]
Problem solved
Thank you.

At /PINCE/libpince, created a directory called **libscanmem** and the following files were copied  `libscanmem.so, misc.py and scanmem.py`

**Comment by RahRah80** [comment]
> It's compiled locally but apparently installed in `/usr`, my memory failed me for this one. I'll be fixing it soon. Does pince work for you right now tho? It has the most importance

Hello.
Now is works, but can't select process.
Can't install distorm3.

**Comment by korcankaraokcu** [comment]
Scanmem is now installed locally, it won't interfere with the system's GameConqueror or scanmem version

**Comment by cglmrfreeman** [comment]
Getting similar results in SUSE
```Traceback (most recent call last):
  File "/home/rob/gits/PINCE/PINCE.py", line 5615, in <module>
    window = MainForm()
  File "/home/rob/gits/PINCE/PINCE.py", line 411, in __init__
    self.backend = Scanmem(libscanmem_path)
  File "/home/rob/gits/PINCE/libpince/libscanmem/scanmem.py", line 46, in __init__
    self._lib = ctypes.CDLL(libpath)
  File "/usr/lib64/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/XXX/gits/PINCE/libpince/libscanmem/libscanmem.so: cannot open shared object file: No such file or directory
```

**Comment by cglmrfreeman** [comment]
As the instructions tell you to blindly run `install_pince.sh` as root (including installing PIP packages as root), without much verbose output, it's hard to tell how I personally have failed to do anything. I will debug the install script to see how it ifails.

**Comment by korcankaraokcu** [comment]
Yeah, that success message is still problematic, sometimes misleads people. About intltool, I'll setup a fresh SUSE virtual machine to check the issue soon

**Comment by korcankaraokcu** [comment]
Which SUSE version are you running btw?

**Comment by cglmrfreeman** [comment]
Tumbleweed

**Comment by korcankaraokcu** [comment]
A fresh install showed that it needs more than just intltool, I've updated the installation dependencies. Hope it works for you, let me know if something goes wrong

**Comment by cglmrfreeman** [comment]
@korcankaraokcu Wait what
https://github.com/korcankaraokcu/PINCE/blob/5278202425c7cd1c1c5f04a26c3dd9b450bd7b7f/install_pince.sh#L69
Only SUSE would need gcc and make on a fresh install and none of the others? Really?

**Comment by korcankaraokcu** [comment]
Yeah, I was surprised as well. Try using the latest tumbleweed online installer on a VM and see for yourself

**Comment by cglmrfreeman** [comment]
> Yeah, I was surprised as well. Try using the latest tumbleweed online installer on a VM and see for yourself

That's not quite what I meant. Debian, Fedora, and Arch won't need gcc or make?

**Comment by cglmrfreeman** [comment]
Ah, fair enough
