### ISSUE TITLE
Cannot use Print Screen button in PINCE UI

### ISSUE THREAD

**Issue by jaredballou** [korcankaraokcu/PINCE#137]
Since the keyboard shortcut update, I am no longer able to use the Print Screen key and OS functionality within the app.

If I give the UI focus, I am unable to use the key.

If I select another window, Print Screen works fine and I am able to take screenshots.

I am on Ubuntu 20.04 if that matters.

**Comment by korcankaraokcu** [comment]
I cannot reproduce this with a clean installation of Ubuntu 20.04. I've also tried with Kubuntu to see if it was gnome related but apparently not, it works without an issue in both systems. I also cannot seem to find anything related to keyboard package we are using right now. I'll be leaving this issue open for now as others might encounter it as well

**Comment by brkzlr** [comment]
@jaredballou Does this still happen with the newest releases?
