### ISSUE TITLE
Pince doesn't start

### ISSUE THREAD

**Issue by Alib234** [korcankaraokcu/PINCE#138]
So after running the install script then running pince by doing ```sh PINCE.sh``` it gives this and then doesn't do anything
```
/home/alib234/Gits/PINCE/libpince/libscanmem/misc.py:24: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
QStandardPaths: runtime directory '/run/user/1000' is not owned by UID 0, but a directory permissions 0700 owned by UID 1000 GID 985
QSocketNotifier: Can only be used with threads started with QThread
QStandardPaths: runtime directory '/run/user/1000' is not owned by UID 0, but a directory permissions 0700 owned by UID 1000 GID 985
/home/alib234/Gits/PINCE/PINCE.py:5613: Warning: cannot register existing type 'GtkWidget'
  app = QApplication(sys.argv)
/home/alib234/Gits/PINCE/PINCE.py:5613: Warning: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
  app = QApplication(sys.argv)
/home/alib234/Gits/PINCE/PINCE.py:5613: Warning: cannot register existing type 'GtkBuildable'
  app = QApplication(sys.argv)
/home/alib234/Gits/PINCE/PINCE.py:5613: Warning: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
  app = QApplication(sys.argv)
/home/alib234/Gits/PINCE/PINCE.py:5613: Warning: g_once_init_leave: assertion 'result != 0' failed
  app = QApplication(sys.argv)
/home/alib234/Gits/PINCE/PINCE.py:5613: Warning: g_type_register_static: assertion 'parent_type > 0' failed
  app = QApplication(sys.argv)
```

**Comment by korcankaraokcu** [comment]
Which distro are you on?

**Comment by Alib234** [comment]
I'm on arch linux

**Comment by Alib234** [comment]
so I finally did something towards trying to make this work
I added
`import gi
gi.require_version('Gtk', '4.0')`
below the `import sys`

now it tries to start but can't connect to display?

like if I run `./PINCE.sh`
it gives me `QStandardPaths: runtime directory '/run/user/1000' is not owned by UID 0, but a directory permissions 0700 owned by UID 1000 GID 985
QSocketNotifier: Can only be used with threads started with QThread
QStandardPaths: runtime directory '/run/user/1000' is not owned by UID 0, but a directory permissions 0700 owned by UID 1000 GID 985
Invalid MIT-MAGIC-COOKIE-1 key

(python3:114608): Gtk-WARNING **: 03:50:53.268: cannot open display: :0`

and if I run `QT_QPA_PLATFORM=xcb ./PINCE.sh`
it gives me `Invalid MIT-MAGIC-COOKIE-1 key
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

/home/alib234/Gits/PINCE/PINCE.sh: line 25: 114756 Aborted                 sudo -E python3 PINCE.py`

so not sure what's wrong after that one change but it seems to go further than without it

**Comment by Fruitloopins** [comment]
I fixed this by just adding sudo before sh PINCE.sh

**Comment by korcankaraokcu** [comment]
@Fruitloopins Thanks for the input, I've updated readme accordingly

**Comment by korcankaraokcu** [comment]
Linking this to #153

If you are still getting this error you can try the solutions in there

**Comment by korcankaraokcu** [comment]
Both installation and launcher scripts has been updated, there's no need to use sudo beforehand anymore
