### ISSUE TITLE
I try to attach to a process and get this:  EOFError: Ran out of input

### ISSUE THREAD

**Issue by BZER0** [korcankaraokcu/PINCE#139]
![image](https://user-images.githubusercontent.com/76451333/186991295-f13c7fcd-78ef-434d-92a0-8ab1ab94efa3.png)

**Comment by k0xyy** [comment]
edit - i am running Fedora 36

**Comment by k0xyy** [comment]
This is what it returns when i exit after it bugs out
![image](https://user-images.githubusercontent.com/76451333/186992144-94745550-f2c6-4dbe-a373-ea5a1394a825.png)

**Comment by brkzlr** [comment]
You seem to be missing the distorm3 module judging from the error message in the first picture.

Fedora isn't supported right now so the install script might have failed on installing the dependencies.

Try installing distorm3 and any other dependency from terminal error messages manually and try again.

**Comment by korcankaraokcu** [comment]
This issue has been fixed with the latest updates, try running `install_pince.sh` again
