### ISSUE TITLE
"Killed by singal 11."

### ISSUE THREAD

**Issue by FoxMaccloud** [korcankaraokcu/PINCE#144]
Hi.

I'm using Pince and after using it for a while the application just dies and my terminal shows;
```
0.0006365776062011719
UPDATED MEMORYVIEW IN:0.03457021713256836
..........info: we currently have 19871 matches.
Last command: c
^running
*running,thread-id="all"
0.0012814998626708984
error: 
Killed by signal 11.
```

I have installed Pince via the [AUR](https://aur.archlinux.org/packages/pince-git).
I'm running Linux Arch 5.19.13-arch1-1.

**Comment by korcankaraokcu** [comment]
It's a known issue for libscanmem. If it persists during multiple sessions, you might want to use Game Conqueror instead and copy paste the addresses into PINCE for debugging
