### ISSUE TITLE
Linux Mint Debian Edition 5 error running PINCE.sh

### ISSUE THREAD

**Issue by RahRah80** [korcankaraokcu/PINCE#152]
/home/rah-rah/GAMES/cheat/PINCE/PINCE.py:5613: Warning: cannot register existing type 'GtkWidget'
  app = QApplication(sys.argv)
/home/rah-rah/GAMES/cheat/PINCE/PINCE.py:5613: Warning: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
  app = QApplication(sys.argv)
/home/rah-rah/GAMES/cheat/PINCE/PINCE.py:5613: Warning: cannot register existing type 'GtkBuildable'
  app = QApplication(sys.argv)
/home/rah-rah/GAMES/cheat/PINCE/PINCE.py:5613: Warning: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
  app = QApplication(sys.argv)
/home/rah-rah/GAMES/cheat/PINCE/PINCE.py:5613: Warning: g_once_init_leave: assertion 'result != 0' failed
  app = QApplication(sys.argv)
/home/rah-rah/GAMES/cheat/PINCE/PINCE.py:5613: Warning: g_type_register_static: assertion 'parent_type > 0' failed
  app = QApplication(sys.argv)

I'm using Linux Mint Debian Edition 5.
Last i was using with the Ubuntu Edition and was working fine.
I just can't find what is missing to install.

Thank you.

**Comment by korcankaraokcu** [comment]
try changing env vars like this before you start PINCE
```bash
export QT_QPA_PLATFORMTHEME=gtk3
export QT_STYLE_OVERRIDE=gtk3
```

**Comment by RahRah80** [comment]
Thank you.
Worked like a charmed.

I added to PINCE.sh so i could run directly from nemo.

Thank you once again.

**Comment by korcankaraokcu** [comment]
I think I'll also add it to master after some testing on my end because I remember this issue being posted in the past

**Comment by korcankaraokcu** [comment]
Apparently overriding `QT_QPA_PLATFORMTHEME` crashes pince on my end

@RahRah80 Can you try exporting only `QT_STYLE_OVERRIDE` and tell me if it works for you?

**Comment by RahRah80** [comment]
Hello.
How do i do that?

**Comment by korcankaraokcu** [comment]
Add only `export QT_STYLE_OVERRIDE=gtk3` into your PINCE.sh script and discard `QT_QPA_PLATFORMTHEME`

**Comment by RahRah80** [comment]
Hello.

Thank you.

With me doesn't work either.

QStandardPaths: runtime directory '/run/user/1000' is not owned by UID 0,
but a directory permissions 0700 owned by UID 1000 GID 1000
QApplication: invalid style override 'gtk3' passed, ignoring it.
Available styles: cleanlooks, gtk2, cde, motif, plastique, qt5ct-style,
Windows, Fusion
/home/rah-rah/GAMES/cheat/PINCE/PINCE.py:5613: Warning: cannot register
existing type 'GtkWidget'
  app = QApplication(sys.argv)
/home/rah-rah/GAMES/cheat/PINCE/PINCE.py:5613: Warning:
g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE
(instance_type)' failed
  app = QApplication(sys.argv)
/home/rah-rah/GAMES/cheat/PINCE/PINCE.py:5613: Warning: cannot register
existing type 'GtkBuildable'
  app = QApplication(sys.argv)
/home/rah-rah/GAMES/cheat/PINCE/PINCE.py:5613: Warning:
g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE
(interface_type)' failed
  app = QApplication(sys.argv)
/home/rah-rah/GAMES/cheat/PINCE/PINCE.py:5613: Warning: g_once_init_leave:
assertion 'result != 0' failed
  app = QApplication(sys.argv)
/home/rah-rah/GAMES/cheat/PINCE/PINCE.py:5613: Warning:
g_type_register_static: assertion 'parent_type > 0' failed
  app = QApplication(sys.argv)

**Comment by korcankaraokcu** [comment]
Thanks for the info, I'm linking this to #153
