### ISSUE TITLE
Process stopped

### ISSUE THREAD

**Issue by RahRah80** [korcankaraokcu/PINCE#154]
Hello.

When using PINCE it keeps stopping the process and i have to press F3 to continue and some games are impossible to play.
This happens with unity games so far.

Is there a way to prevent or disable?

Thank you

**Comment by korcankaraokcu** [comment]
This is most likely caused by a signal, gdb catches all signals and stops the process on some of them. You should see something like `*stopped,reason="signal-received",signal-name="SIGINT",signal-meaning="Interrupt"` in your console output whenever the process is stopped. Can you confirm this and tell me which signal causes the stop?

**Comment by RahRah80** [comment]
Hello

Never checked the console.
But yesterday i was playing Crystal Caves HD from GOG (made with Unity) i
was only doing memory searches and didn't used the debugger and the game
was constantly stopping.

Later today i'll check and send you the output.

Thank you.

**Comment by RahRah80** [comment]
Hello.

~"\nThread "
~"18 \"Finalizer\" received signal SIGXCPU, CPU time limit exceeded.\n"
~"[Switching to Thread 0x7fc4d4ff9700 (LWP 13580)]\n"
~"0x00007fc5aea8512a in sigsuspend () from
/lib/x86_64-linux-gnu/libc.so.6\n"
**stopped,reason="signal-received",signal-name="SIGXCPU",signal-meaning="CPU
time limit exceeded"*
,frame={addr="0x00007fc5aea8512a",func="sigsuspend",args=[],from="/lib/x86_64-linux-gnu/libc.so.6",arch="i386:x86-64"},thread-id="18",stopped-threads="all",core="4"
~"[Switching to thread 18 (Thread 0x7fc4d4ff9700 (LWP 13580))]\n"
~"#0  0x00007fc5aea8512a in sigsuspend () from
/lib/x86_64-linux-gnu/libc.so.6\n"
=thread-selected,id="18",frame={level="0",addr="0x00007fc5aea8512a",func="sigsuspend",args=[],from="/lib/x86_64-linux-gnu/libc.so.6",arch="i386:x86-64"}

CPU reached the limit..

**Comment by korcankaraokcu** [comment]
You need to ignore `SIGXCPU` within gdb. You can do that by using the `gdbinit` file provided by pince

Here's the wiki page for it:
 https://github.com/korcankaraokcu/PINCE/wiki/Init-files

**Comment by RahRah80** [comment]
Hello

Added handle SIGXCPU nostop noprint to gdbinit file and the works fine, no
more stopping.

Thank you.

**Comment by korcankaraokcu** [comment]
My pleasure, have a nice day

**Comment by RahRah80** [comment]
Thank you and a nice day too you to!
