### ISSUE TITLE
Add SIG34 to the ignore Handle Signal GUI

### ISSUE THREAD

**Issue by alexisramon3** [korcankaraokcu/PINCE#155]
My games keeps pausing because of this signal, I usually do "handle SIG34 nostop noprint" to fix it in the GDB console but I think having it in the Handle Signal setting GUI would make it simpler. I'd do it myself but I don't have Qt or whatever. Kind regards!

**Comment by korcankaraokcu** [comment]
This started to be a very common issue. We are discussing a permanent solution in the pince discord server right now, the link is in the readme file if you want to provide ideas

Meanwhile, you can use init files to disable that signal as a workaround:
https://github.com/korcankaraokcu/PINCE/wiki/Init-files
