### ISSUE TITLE
Crashes every time I try to edit a value

### ISSUE THREAD

**Issue by Anonymous3-a** [korcankaraokcu/PINCE#158]
I am trying to edit a value in the PICO-8, but every time I try, PINCE crashes for some reason. I am on Arch Linux, using GNOME, and have no other apps open (other than screen -R)

**Comment by korcankaraokcu** [comment]
Can you share the console log when it crashes? I'd also appreciate detailed steps to reproduce the bug

**Comment by korcankaraokcu** [comment]
Any updates on this?

**Comment by Anonymous3-a** [comment]
Oh, sorry! I didn't notice you responded, I got a new computer so I'll see if it will crash this time, and if it does I'll send it

**Comment by Anonymous3-a** [comment]
Ok, I found the error:
```
/home/[USERNAME CENSORED]/Software/PINCE/PINCE.py:1988: Warning: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-fallback-icon-theme'
  self.buttonBox.addButton(button)
free(): invalid pointer
error: 
Killed by signal 6.
```

**Comment by korcankaraokcu** [comment]
Exactly the same issue with #159 and I can't seem to reproduce, setups are the same too

**Comment by korcankaraokcu** [comment]
Try inserting this to the beginning of pince.py
```
import gi

gi.require_version('Gtk', '3.0')
```
This apparently worked for someone else, hopefully it works for you too

**Comment by korcankaraokcu** [comment]
GTK version mismatch issues are fixed. Update your project with `git pull` and try again

**Comment by Xoslorg** [comment]
With the latest commit it works perfectly.
Thank you very much.

**Comment by Anonymous3-a** [comment]
Works great! Thank you!

**Comment by korcankaraokcu** [comment]
Glad this one is over too, closing this issue. Have a nice day!
