### ISSUE TITLE
Crash when press settings icon and Edit labels

### ISSUE THREAD

**Issue by Xoslorg** [korcankaraokcu/PINCE#159]
/opt/PINCE/GUI/SettingsDialog.py:315: Warning: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-fallback-icon-theme'
  self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
error:

**Comment by Xoslorg** [comment]
/opt/PINCE/./PINCE.py:1949: Warning: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-fallback-icon-theme'
  self.buttonBox.addButton(button)
error: 
Killed by signal 11.

**Comment by korcankaraokcu** [comment]
I cannot seem to reproduce this bug, what's your distro?

**Comment by Xoslorg** [comment]
Archlinux with gnome

**Comment by Xoslorg** [comment]
[](https://youtu.be/yyEl28C-Yxs)

**Comment by korcankaraokcu** [comment]
I've done a clean installation of archlinux gnome and can confirm that this issue exists for the specified distro

I've fixed this issue by running `export QT_QPA_PLATFORMTHEME=qt5ct` on my end. Can you try running this before running pince and tell me if it works? I think you also need to install `qt5ct` before doing so

**Comment by Xoslorg** [comment]
Thanks, the problem is solved perfectly on my laptop, at home I will try with the desktop.

**Comment by korcankaraokcu** [comment]
Thanks for confirming, apparently this is a gnome related issue. There's a PR that upgrades the pyqt version to 6, if that doesn't fix the issue I'll try to include this in the installation script. Have a nice day

**Comment by korcankaraokcu** [comment]
Apparently this issue doesn't exist in pyqt6, that's a relief

**Comment by Xoslorg** [comment]
With last updates get same error.
/opt/PINCE/GUI/SettingsDialog.py:314: Warning: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-fallback-icon-theme'
  self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
error: 
Killed by signal 6.

**Comment by korcankaraokcu** [comment]
I've done another clean installation of archlinux gnome and unfortunately cannot reproduce the bug above, it's gone after pyqt6 upgrade for me. Maybe try the solution above with qt6ct?

**Comment by Xoslorg** [comment]
With clean installation
/opt/PINCE/GUI/SettingsDialog.py:314: Warning: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-fallback-icon-theme'
  self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
error: 
Killed by signal 11.

with clean installation and qt6ct
/opt/PINCE/GUI/SettingsDialog.py:314: Warning: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-fallback-icon-theme'
  self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
free(): invalid pointer
error: 
Killed by signal 6.

with clean installation and qt6ct & export QT_QPA_PLATFORMTHEME=qt6ct
/opt/PINCE/GUI/SettingsDialog.py:314: Warning: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-fallback-icon-theme'
  self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
free(): invalid pointer
error: 
Killed by signal 6.

**Comment by korcankaraokcu** [comment]
https://github.com/korcankaraokcu/PINCE/issues/116

Apparently Offpics has been able to fix it by installing qt5ct and launching it, maybe try that with qt6ct? You probably already installed it, telling that just in case if you haven't launched yet

**Comment by Xoslorg** [comment]
same result with qt5rc
/opt/PINCE/GUI/SettingsDialog.py:314: Warning: g_object_get_is_valid_property: object class 'GtkSettings' has no property named 'gtk-fallback-icon-theme'
  self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
free(): invalid pointer
error: 
Killed by signal 6.

**Comment by korcankaraokcu** [comment]
No I meant qt6ct and launching it

**Comment by Xoslorg** [comment]
Yes, first with qt6ct.

**Comment by korcankaraokcu** [comment]
Try inserting this to the beginning of pince.py
```
import gi

gi.require_version('Gtk', '3.0')
```
This apparently worked for someone else, hopefully it works for you too

**Comment by Xoslorg** [comment]
Good, I just tried it and now it works, thank you very much.

**Comment by korcankaraokcu** [comment]
This will be most likely added to pince soon, I'll notify you

**Comment by korcankaraokcu** [comment]
The patch is up, you can revert your local changes and update the project with `git pull`
