### ISSUE TITLE
Can it sometimes replace CE  on MIngw working games

### ISSUE THREAD

**Issue by gmctl** [korcankaraokcu/PINCE#168]
rt

**Comment by Bloodiko** [comment]
No, 
It is not designed to be used on windows in any way. 
Thus you will run into issues while installing and running. 

If you are on windows, use CE. 

Pince is not as powerful as CE yet. 

Also, it's much easier to get answered such questions over on Discord (link in Readme), helping to keep this issue section clean of FAQ Questions.

**Comment by korcankaraokcu** [comment]
Bloodiko is mostly right. You might be able to run it if the requirements are met, such as dependencies and availability of `/proc/$pid/mem`. Even if you somehow manage to run pince under mingw, unfortunately we are not planning to support it. So you'll be on your own
