### ISSUE TITLE
Can't run after installation 

### ISSUE THREAD

**Issue by KurenaiGoukami** [korcankaraokcu/PINCE#171]
Help, I just installed Pince and it's giving me this error, any solution? I'm on PoP_OS if it is relevant
![Screenshot from 2023-03-08 23-49-50](https://user-images.githubusercontent.com/92426814/223879212-9b01b3b9-8e23-4e12-92ae-43547f14580b.png)

**Comment by korcankaraokcu** [comment]
Why do you have a pince folder within another pince folder?

**Comment by KurenaiGoukami** [comment]
> That's very weird, I can't seem to replicate this on my end. Pop OS isn't officially supported but nothing within the installation should cause this. What's your python version?

python version is 3.10.6 I believe

**Comment by KurenaiGoukami** [comment]
> Why do you have a pince folder within another pince folder?

ignore my dumbness I was frustrated and must have done that

**Comment by brkzlr** [comment]
Does it work after deleting that inner PINCE folder?

**Comment by korcankaraokcu** [comment]
Any updates about this?

**Comment by korcankaraokcu** [comment]
I've interpreted "opened" as in opening a folder at first but you are probably right, it's opening as in being able to launch the project. I've read it a bit too fast, closing now
