### ISSUE TITLE
How do i find an address in the memory viewer? 

### ISSUE THREAD

**Issue by cornflakes6374** [korcankaraokcu/PINCE#175]
im trying to hack plants vs zombies running on wine to get to the limbo page (unused minigames) and the pvz wiki says you have to find an address but i cant find an option to go to an address, can you help me?

**Comment by brkzlr** [comment]
Does this really looks like a valid issue to you?

If you need help on using PINCE, you have the wiki or Discord.

Creating an issue on GitHub is not the way.

**Comment by brkzlr** [comment]
> lol, no need to bite

There's no biting. If they want/need help with PINCE, they can get the help they want faster/better on Discord.
No need to create issues about it on GitHub, otherwise it will get spammy pretty quickly.

**Comment by brkzlr** [comment]
Right click hex view and then "Go To Address" or CTRL+G btw

**Comment by korcankaraokcu** [comment]
> Right click hex view and then "Go To Address" or CTRL+G btw

This is the correct answer

> Does this really looks like a valid issue to you?

@brkzlr is right, you could have watched the tutorial video in the wiki page. Also, for trivial stuff like this one, you'll get faster help in discord

Closing the issue since an answer was provided
