### ISSUE TITLE
This application failed to start because no Qt platform plugin could be initialized

### ISSUE THREAD

**Issue by Kyr4l** [korcankaraokcu/PINCE#178]
i've insalled PINCE, no error were displayed, as soon as i try to start it i get the following error : 
```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, wayland, eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, xcb.

PINCE.sh: line 27: 11914 Aborted                 sudo -E PYTHONDONTWRITEBYTECODE=1 python3 PINCE.py
```

i remember having this issue months ago on debian but i can't remember what i had to do to fix it, i remember installing a package that immediately fixed the issue

**Comment by korcankaraokcu** [comment]
Installation script has been updated, try to reinstall from scratch. Do not use sudo while installing or launching the program, the scripts will handle it for you

**Comment by Kyr4l** [comment]
![image](https://user-images.githubusercontent.com/24955106/235778266-a46a97a0-8b15-4b57-a9d6-7b5d2d71b0c2.png)
it's working now

**Comment by korcankaraokcu** [comment]
Thanks for the confirmation, closing the issue
