### ISSUE TITLE
Incorrect pygdbmi missing error

### ISSUE THREAD

**Issue by awsdert** [korcankaraokcu/PINCE#185]
On manjaro x64 XFCE, was working before I temporarily switched to the "unstable" branch so not sure what's going on here
```
Traceback (most recent call last):
  File "/usr/share/PINCE/PINCE.py", line 41, in <module>
    from libpince import GuiUtils, SysUtils, GDB_Engine, type_defs
  File "/usr/share/PINCE/libpince/GuiUtils.py", line 18, in <module>
    from . import SysUtils, type_defs, common_regexes
  File "/usr/share/PINCE/libpince/SysUtils.py", line 32, in <module>
    from pygdbmi import gdbmiparser
ModuleNotFoundError: No module named 'pygdbmi'
```
![PINCE incorrect missing pygdbmi error](https://github.com/korcankaraokcu/PINCE/assets/7422982/3b14d589-fbb6-44be-8834-edffa2b5e88e)

**Comment by korcankaraokcu** [comment]
Did you try installing pygdbmi by yourself? What about other python packages, are they present?

**Comment by awsdert** [comment]
all the python packages were installed as dependencies, I have not manually installed a single thing of python

**Comment by awsdert** [comment]
Just tried re-building it and that seems to have resolved that particular error, another one popped up though, gonna try a search for all python modules and rebuild them if it has the option, in the mean time in case the new error is unrelated here's the output:
```
Traceback (most recent call last):
  File "/usr/share/PINCE/PINCE.py", line 58, in <module>
    from GUI.MemoryViewerWindow import Ui_MainWindow_MemoryView as MemoryViewWindow
  File "/usr/share/PINCE/GUI/MemoryViewerWindow.py", line 919, in <module>
    from GUI.CustomLabels.FlagRegisterLabel import QFlagRegisterLabel
  File "/usr/share/PINCE/GUI/CustomLabels/FlagRegisterLabel.py", line 21, in <module>
    from PINCE import InputDialogForm
  File "/usr/share/PINCE/PINCE.py", line 85, in <module>
    from keyboard import add_hotkey, remove_hotkey
ModuleNotFoundError: No module named 'keyboard'
```

**Comment by awsdert** [comment]
Yeah rebuilding the AUR related ones appears to have resolved the errors

**Comment by korcankaraokcu** [comment]
I haven't tested the AUR in a long time, tested the installation script tho, it should work. Glad you sorted it out
