### ISSUE TITLE
Not installing properly on arch

### ISSUE THREAD

**Issue by DuCosucosu** [korcankaraokcu/PINCE#192]
When I try to install PINCE on Endeavour OS (arch based) with the installation script I get this message
How can I fix ?

`Your distro is not officially supported! Trying to install anyway.
Please choose your package manager.
1) APT
2) Pacman
3) DNF
4) Zypper
5) None of the above
Choose: 2
avertissement : python-pip-23.1.2-1 est à jour -- ignoré
avertissement : readline-8.2.001-2 est à jour -- ignoré
avertissement : intltool-0.51.0-6 est à jour -- ignoré
avertissement : gdb-13.1-3 est à jour -- ignoré
avertissement : lsb-release-2.0.r48.3cf5103-1 est à jour -- ignoré
 il n’y a rien à faire
Requirement already satisfied: pyqt6 in ./.venv/PINCE/lib/python3.11/site-packages (6.5.1)
Requirement already satisfied: pexpect in ./.venv/PINCE/lib/python3.11/site-packages (4.8.0)
Requirement already satisfied: distorm3 in ./.venv/PINCE/lib/python3.11/site-packages (3.5.2)
Requirement already satisfied: keystone-engine in ./.venv/PINCE/lib/python3.11/site-packages (0.9.2)
Requirement already satisfied: pygdbmi in ./.venv/PINCE/lib/python3.11/site-packages (0.11.0.0)
Requirement already satisfied: keyboard in ./.venv/PINCE/lib/python3.11/site-packages (0.13.5)
Requirement already satisfied: pygobject in ./.venv/PINCE/lib/python3.11/site-packages (3.44.1)
Requirement already satisfied: PyQt6-sip<14,>=13.4 in ./.venv/PINCE/lib/python3.11/site-packages (from pyqt6) (13.5.1)
Requirement already satisfied: PyQt6-Qt6>=6.5.0 in ./.venv/PINCE/lib/python3.11/site-packages (from pyqt6) (6.5.1)
Requirement already satisfied: ptyprocess>=0.5 in ./.venv/PINCE/lib/python3.11/site-packages (from pexpect) (0.7.0)
Requirement already satisfied: pycairo>=1.16.0 in ./.venv/PINCE/lib/python3.11/site-packages (from pygobject) (1.23.0)

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
Downloading scanmem
fatal : ni ceci ni aucun de ses répertoires parents n'est un dépôt git : .git

Error occured while installing PINCE, check the output above for more information
Installation failed.`

**Comment by korcankaraokcu** [comment]
Dİd you follow the installation instructions or just downloaded the project as a zip file?

**Comment by brkzlr** [comment]
Just like Korcan says, you didn't follow the instructions to clone the repository recursively with the `--recursive` flag.

Please also refrain from opening installation issues when you're on an unsupported distro.

**Comment by korcankaraokcu** [comment]
> Please also refrain from opening installation issues when you're on an unsupported distro

It's aight, sometimes it works sometimes it doesn't. However, if it's unsupported, we are not going to include anything done in issues within the installation scripts

**Comment by brkzlr** [comment]
> endeavour is literally just arch with a cool rice it should be supported

Due to the various other distros that we already officially support, we can't start supporting each one as we're trying to do clean tests for every distro that we support.

Plus this can lead to installer script bloat if each new offshoot distro decides to rename packages or supply them differently, even if they're based on a parent distro.

This is the reason why we added the ability for unsupported distros to still use the installer with user input, but more than that we cannot do anything without overwhelming ourselves, so if the installer fails due to missing/renamed packages, it's nothing we can do.

**Comment by korcankaraokcu** [comment]
According to their messages in pince discord chat, following the instructions and using `--recursive` has helped them solve the problem. I'm closing this issue
