### ISSUE TITLE
Icons disappear when PINCE gets executed with root permissions

### ISSUE THREAD

**Issue by korcankaraokcu** [korcankaraokcu/PINCE#2]

**Comment by sriemer** [comment]
You might want to try to use `pkexec` within a separate shell script like GameConqueror does.

**Comment by korcankaraokcu** [comment]
@sriemer Thanks for the suggestion, I really appreciate it but unfortunately, it didn't work well for me(I mean `pkexec` works without any errors but icons are still not visible). The design idea for icons have changed anyways, PINCE will use predefined icons which we will be keeping on a separate directory instead of using system-default icons. I should have updated this issue when we resolved it with @cagriulas, my bad, sorry. I'll update this issue if the problem still occurs after the patch, otherwise I'll close it.

**Comment by korcankaraokcu** [comment]
Closed by this [patch](https://github.com/korcankaraokcu/PINCE/commit/326aa8c3626681d4827c969004af84641722bfda)
