### ISSUE TITLE
[Feature] Display byte array as decimal

### ISSUE THREAD

**Issue by sonofevil** [korcankaraokcu/PINCE#203]
I'm not super familiar with how the value types work. But in some cases it seems like the only way to get the correct values is to access them as a byte array. For example, let's say the relevant integer is 997174221. In hex this is 3b6fabcd. At my address, this is exactly what I find: `3b 6f ab cd`. I can add an address with the data type byte array length 4 to get this value displayed perfectly. However, none of the available integer types display the correct decimal number. They are all completely wrong, and I'm not sure why.

In cheat engine, there is, separately from the "type" option, an option for whether to display as decimal or hex. In PINCE, the display format is tied to the value type. Maybe it shouldn't be.

This extends to scanning btw. It is currently seemingly not possible to find "997174221" even when "3b 6f ab cd" is present in memory.

**Comment by korcankaraokcu** [comment]
> In hex this is 3b6fabcd. At my address, this is exactly what I find: 3b 6f ab cd. I can add an address with the data type byte array length 4 to get this value displayed perfectly. However, none of the available integer types display the correct decimal number. They are all completely wrong, and I'm not sure why

Just tried it, it seems to work fine
![image](https://github.com/korcankaraokcu/PINCE/assets/5638719/9442b516-98e8-4ad3-8dfd-bc2a96ac6906)

Scanning works fine too
![image](https://github.com/korcankaraokcu/PINCE/assets/5638719/26e03923-d1bf-4afd-9033-a860716834be)

Sorry, I can't seem to reproduce this on my own, what's the game you are working on?

> In cheat engine, there is, separately from the "type" option, an option for whether to display as decimal or hex. In PINCE, the display format is tied to the value type. Maybe it shouldn't be

It actually isn't tied design wise, I just disabled the ability to display it as decimal for data types with length, such as strings and byte arrays. Also, just checked how CE handles it, it seems to separate decimals, like an array of decimals, not unified like a single number

**Comment by sonofevil** [comment]
Maybe I haven't explained clearly enough what the problem is. Look at the first screenshot. Is there a way to actually display 997174221 here? It certainly isn't being displayed in your screenshot. I have to copy paste the hex value to a separate hex -> decimal converter.

Same problem in your second screenshot. You are searching for the hex value, not the decimal value. Actually enter 997174221 in the search field and try to find that. No results.

**Comment by korcankaraokcu** [comment]
> Is there a way to actually display 997174221 here?

Yeah, with Int32 type (4-byte). Not separated tho, as I explained above. Search also doesn't support separated decimals

> You are searching for the hex value, not the decimal value. Actually enter 997174221 in the search field and try to find that (obviously untick the "Hex" checkbox). No results.

![image](https://github.com/korcankaraokcu/PINCE/assets/5638719/398328ab-b52e-413c-b1c8-1334c599ab36)

**Comment by sonofevil** [comment]
![Screenshot_20230827_210104](https://github.com/korcankaraokcu/PINCE/assets/19374890/b700a090-d062-4f76-98f0-ec30dc19ece1)
![Screenshot_20230827_210228](https://github.com/korcankaraokcu/PINCE/assets/19374890/f21763ed-791d-411c-adeb-2cbc8a268d44)

> separated decimals

I don't know what that means.

**Comment by korcankaraokcu** [comment]
The issue above is an endianness issue like hellidox mentioned

![image](https://github.com/korcankaraokcu/PINCE/assets/5638719/728dbf14-548c-4869-b719-5774993391db)

Scanmem operates with host endian setting by default. Are you trying to run something that your OS doesn't support? Like a game that runs in an emulator. I could expose scanmem endianness setting to the GUI if you want. Sorry for the late reply btw, some other issues got me distracted

> I don't know what that means

Like array of bytes but it's decimals instead

**Comment by sonofevil** [comment]
Thanks, I think I understand the issue now.

And yes, I'm trying to edit the memory of a windows game run via Proton. Not an emulator, but not native either.

Having a GUI option for endianness would be very helpful for my use case, but it sounds like it's more niche than I thought.

**Comment by korcankaraokcu** [comment]
I could add that, no problem. Are you having any difficulties with other functionalities due to that? Such as debugging?

**Comment by sonofevil** [comment]
No, I'm merely looking to manipulate ingame values. People running RPCS3 on Windows can use Cheat Engine for that, but that's not an option on Linux because apps running in Wine aren't exposed to Linux-native processes. But the addresses are the same so I'm trying to compile address lists that can be used with PINCE.

**Comment by korcankaraokcu** [comment]
Yeah, ceserver might work better with non-native targets

I've implemented endianness btw. Pull the latest changes and enjoy the new feature

**Comment by sonofevil** [comment]
> Yeah, ceserver might work better with non-native targets
> 
> I've implemented endianness btw. Pull the latest changes and enjoy the new feature

Awesome, thank you.
