### ISSUE TITLE
Dragging an item in the address table crashes PINCE (Fedora/GNOME)

### ISSUE THREAD

**Issue by ThubLives** [korcankaraokcu/PINCE#204]
Wondering if I could reorder the entries in the address table, I tried to drag an item and PINCE crashed with "killed by signal 11."

**Comment by korcankaraokcu** [comment]
I can't seem to reproduce this on my end. Can you share your specs and the name of the application you are using pince with?

**Comment by ThubLives** [comment]
It's happening for me on Endless Sky 0.9.16.1, installed by RPM package.

System specs:
Fedora 38 Workstation x86_64
Gnome 44.2 on Wayland
16 GB RAM
Intel Core i5-3400U
Intel® HD Graphics 4400 (HSW GT2)

**Comment by korcankaraokcu** [comment]
I've switched to my Fedora virtual machine and tested it, you are absolutely right! That's apparently a Qt bug related to gnome:

https://gitlab.gnome.org/GNOME/mutter/-/issues/2715

There's not much to do since it's unrelated to pince but feel free to post any solution you can find. I'll keep the issue open

**Comment by ThubLives** [comment]
> I've switched to my Fedora virtual machine and tested it, you are absolutely right! That's apparently a Qt bug related to gnome:
> 
> https://gitlab.gnome.org/GNOME/mutter/-/issues/2715
> 
> There's not much to do since it's unrelated to pince but feel free to post any solution you can find. I'll keep the issue open

I'm not convinced this issue is relevant.  Firstly, I already have a Gnome build with the patch that fixes this Gnome issue, and secondly, I haven't been able to reproduce this problem with any other KDE applications.  In particular, I tried some of the apps called out in that Gnome issue, but they work fine.

Clearly this does have some connection with Gnome as I have installed KDE on my Fedora 38 system and tested directly in a Wayland KDE session and cannot reproduce the drag-and-drop crash in PINCE.

All I'm saying is that while this likely is a Gnome bug, it doesn't seem to be covered by that particular Gnome issue.

**Comment by korcankaraokcu** [comment]
> All I'm saying is that while this likely is a Gnome bug, it doesn't seem to be covered by that particular Gnome issue.

Yeah, that was the first one that caught my attention, that's why I posted it. I've re-checked the code after you mentioned and apparently we don't override any [QDrag](https://doc.qt.io/qt-6/qdrag.html) related events, we don't even import it. So yeah, it's most likely a Gnome bug

**Comment by korcankaraokcu** [comment]
Any updates with this one? You can use the AppImage we provide in the releases to test

**Comment by ThubLives** [comment]
Recent builds don't seem to trigger the crash; not sure if this is due to changes in PINCE or Gnome, but either way, it's working now.
