### ISSUE TITLE
Pince is screwing up with locals (decimal numeric values are not parsed correcty)

### ISSUE THREAD

**Issue by gdonval** [korcankaraokcu/PINCE#225]
You have a locals problem.

![image](https://github.com/korcankaraokcu/PINCE/assets/2644113/d3e15431-b2c7-4099-838a-3edb35920b05)

leads to:

![image](https://github.com/korcankaraokcu/PINCE/assets/2644113/5a60394d-bbfe-4033-b2c7-4daa1f4cf64d)

Before you ask what witchcraft happened there, it's probably Qt trying to be cute and perform absolutely nonsensical conversions for you (however I look at the problem, it's the wrong way around). 

My locals on that computer is a Latin European one. With such locals, the conventional decimal separator is **not** `.` but `,`, e.g. `1,234567`, not `1.234567`. `LC_NUMERIC=C` (the usual way to work around this kind of problems) does not work.

This report is **NOT** about supporting those locals (sorry for the emphasis).

This report is about a **bug**: Qt reads `"1.234567"` as an input and then does a conversion to `"1,234567"` that makes parsing fail: `float("1,234567")` fails.

**Comment by gdonval** [comment]
Cool! Thanks for having a look at this! :)

**Comment by korcankaraokcu** [comment]
Meanwhile, you can disable the lines 1190 and 1191 and replace them with a `pass`. I'll try to come up a generalized solution for different locales

**Comment by korcankaraokcu** [comment]
https://github.com/korcankaraokcu/PINCE/commit/18461fb08e1002e7d7367af153562c2b2972a4fa fixes this issue. Feel free to report any other locale inconsistencies. Also, the idea came from @brkzlr, kudos to him
