### ISSUE TITLE
UI Dark mode

### ISSUE THREAD

**Issue by jamesbaw1** [korcankaraokcu/PINCE#228]
Using Linux Mint 21.2, some UI elements are white with white text with the default dark theme (Mint-Y-Dark-Sand). Not a huge issue though.

**Comment by korcankaraokcu** [comment]
Yeah, some other distros have similar palette problems as well. Can you post a screenshot?

**Comment by korcankaraokcu** [comment]
You can choose the custom dark theme in the settings now
