### ISSUE TITLE
cant start PINCE from terminal

### ISSUE THREAD

**Issue by Tuskiurhil** [korcankaraokcu/PINCE#231]
I have recently built PINCE from source and when trying to run it through the terminal I am receiving the following traceback.

![image](https://github.com/korcankaraokcu/PINCE/assets/79027579/6ace9a5a-c933-4be8-bb73-4ded8104a1e4)

**Comment by korcankaraokcu** [comment]
Delete your settings file, that should fix it

**Comment by korcankaraokcu** [comment]
I've also released a patch to fix this automatically, enjoy

**Comment by Tuskiurhil** [comment]
> Delete your settings file, that should fix it

> I've also released a patch to fix this automatically, enjoy

Worked like a charm. Thank you. Deleting the settings file didn't even cross my mind.
