### ISSUE TITLE
Unable to install an update on Arch Linux

### ISSUE THREAD

**Issue by ZonicTrout** [korcankaraokcu/PINCE#251]
**System Information**:
Arch Linux (`uname -r` is 6.8.8-arch1-1)
Migrating to Home-Manager Package management (not on the pince package though)

**Issue**
I tried to update the pince package using yay, but I was met with a build error message (Logs will be provided). I then tried to clone the pince-git (AUR) repo and update it using makepkg. However, when answering `y` to the `Recompile libscanmem` prompt, I get build error messages.

**How to reproduce** 
Run
`git clone https://aur.archlinux.org/pince-git.git  && cd pince-git && echo "y" | makepkg --clean -f`

**Logs**:
`echo "y" | makepkg --clean -f > stdout.txt 2> stderr.txt`
[stderr.txt](https://github.com/korcankaraokcu/PINCE/files/15191656/stderr.txt)
[stdout.txt](https://github.com/korcankaraokcu/PINCE/files/15191657/stdout.txt)

**What I suspect the error is**:
In the output line
`libtool: link: /home/zonictrout/.nix-profile/bin/nm -B  .libs/commands.o .libs/procmem.o .libs/handlers.o .libs/interrupt.o .libs/maps.o .libs/scanmem.o .libs/scanroutines.o .libs/sets.o .libs/targetmem.o .libs/value.o   ./.libs/libutil.a |  | /usr/bin/sed 's/.* //' | sort | uniq > .libs/libscanmem.exp`
There are two pipes with nothing in between them which is the error suggested by the messsage 
`./libtool: eval: line 1886: syntax error near unexpected token `|'`
I would try to fix the Makefile, but I cannot understand how they work :( and couldn't fix it myself. 

This could be the result of a different nm executable (`which nm`  gives `/home/zonictrout/.nix-profile/bin/nm`), but I have no idea how that could affect anything.

**Apology**:
Sorry, I am still new to posting Github issues, so I am sorry if I made a formatting mistake (I couldn't find the formatting document for this project)

**Comment by brkzlr** [comment]
We're not directly responsible for the AUR package, sorry.

Try contacting the aur package maintainer.

**Comment by ZonicTrout** [comment]
Oh, ok! Should I delete the issue, or should I leave it up?

**Comment by brkzlr** [comment]
I'll close it, np.

**Comment by ZonicTrout** [comment]
Thanks!

**Comment by korcankaraokcu** [comment]
You can use the installation script instead

**Comment by ZonicTrout** [comment]
True, but I usually try to keep all of my packages installed with package managers to simplify updates and removals. Thank You for the suggestion though!

**Comment by brkzlr** [comment]
Apart from a few packages installed using pacman, the installer puts everything in a venv, so removing PINCE folder uninstalls it without leaving anything behind, except some user configs in XDG standard paths.

These packages are: `python-pip qt6-tools gdb lsb-release pkgconf gobject-introspection-runtime` so probably only qt6-tools and gobject will be extra if you decide to no longer use PINCE.

**Comment by brkzlr** [comment]
AppImage support is incoming very soon as well, so you can use that if you want to use PINCE without needing the code to modify or contribute and then get rid of it as easily as deleting the AppImage.

**Comment by ZonicTrout** [comment]
I really appreciate all the work the contributors have put into making it moduler, but the issue lies in the fact that not every project does the same. Some do it like you do, but many others have strange and unique ways of installing and uninstalling. I use package managers for the standardization they provide. 
Thnk you anyway though! I had no idea your project was so modular!
