### ISSUE TITLE
Error gdb after selecting a process

### ISSUE THREAD

**Issue by X-Keyscore** [korcankaraokcu/PINCE#255]
Error in PINCE gdb:
```
~"\nThread "
~"1 \"Main\" received signal SIGILL, Illegal instruction.\n"
~"0x0000000151cc3416 in ?? () from target:/home/xkeyscore/.local/share/Steam/steamapps/common/Call of Duty WWII/s2_mp64_ship.exe\n"
*stopped,reason="signal-received",signal-name="SIGILL",signal-meaning="Illegal instruction",frame={addr="0x0000000151cc3416",func="??",args=[],from="target:/home/xkeyscore/.local/share/Steam/steamapps/common/Call of Duty WWII/s2_mp64_ship.exe",arch="i386:x86-64"},thread-id="1",stopped-threads="all",core="11"
```
The type of process:

`xkeyscore   30729  0.0  0.0  11780  2560 pts/1    S+   15:34   0:00 grep --color=auto Main`

I think this is due to a compatibility problem but can we solve this problem?
I managed to observe the process with gameconqueror and modify values but I would like to be able to use PINCE which offers more possibilities.

**Comment by korcankaraokcu** [comment]
Does `SIGILL` signal stop your process constantly when you attach or is there something else wrong with the signal?

**Comment by X-Keyscore** [comment]
The process I want to observe (s2_mp64_ship.exe) freezes when I want to attach the process PINCE indicates stopped but if I attach another process which is valid, s2_mp64_ship.exe stop freezing.

**Comment by brkzlr** [comment]
1. Just as an FYI, the process you listed is not correct. You just listed the grep process you ran to find the process. Main is the thread name btw, not the name of the process.
2. Try putting `SIGILL` in the signal ignore list in PINCE's settings. If it still doesn't work or crashes after that, it's a gdb issue.

Most likely CoD WW2 is doing some non-standard stuff that emits the signal and gdb is catching it.

**Comment by korcankaraokcu** [comment]
I was going to say what @brkzlr already mentioned. We even have a wiki page dedicated for signal issues:

https://github.com/korcankaraokcu/PINCE/wiki/PROCESS-IS-FREEZING-CONSTANTLY

**Comment by X-Keyscore** [comment]
ok, sorry but it's because PINCE displays Main as the process name.
I've already tried to ignore the sigkill but unfortunately it doesn't change anything.

**Comment by brkzlr** [comment]
`SIGKILL` is a different signal and can not be ignored in most cases. The signal in question is `SIGILL`

**Comment by X-Keyscore** [comment]
yes I made a mistake I had just corrected it

**Comment by brkzlr** [comment]
Did you disable Stop & Print for `SIGILL`? If yes and it still freezes/crashes, then I'm sorry but it's a gdb issue.

Probably game has some anti-debugs in it and intentionally does illegal instructions to stop debuggers.

**Comment by X-Keyscore** [comment]
ok so you were right I was very wrong I unchecked sigkill instead of sigill.

So I would say that it's good because PINCE works but the game is frozen, maybe there should be a way to easily disconnect and reconnect a thead

**Comment by brkzlr** [comment]
If "Pass to Program" is unchecked, try checking it as the game might except the signal and it's paused. Try using F3 to continue the process as well.

**Comment by X-Keyscore** [comment]
ok so I checked the passage to the program for sigill and sigsegv and unchecked print & stop, now it works thank you very much for your help is thanks to the creator of this very powerful tool.
