### ISSUE TITLE
[Feature request] Add the ability to limit memory scanning to a specific memory range

### ISSUE THREAD

**Issue by Chikmyvoltage** [korcankaraokcu/PINCE#266]
It is frustrating when memory scanning for an unknown value within a big game and the results count climbs to a point that PINCE crashes on the next scan. I presume memory fills up so quickly that the OOM killer gets to work and kills PINCE. I checked and didn't find an issue mentioning this so it's probably on my end.

However, the functionality of limiting memory scans to specific regions like in CE would be very nice and would most likely solve my issue, so I hope this gets added soon.

**Comment by korcankaraokcu** [comment]
You can use scan scope option to limit your scans but yeah, there's no option to select the regions manually. Scanmem has this feature as I remember, PINCE can expose this setting as well. Thanks for the request, I'll be considering this one in-depth soon

**Comment by korcankaraokcu** [comment]
This feature has been implemented. Within the local dev installation folder, pull the latest changes with `git pull` and then reinstall pince locally with `sh install.sh`. You'll be prompted about reinstalling scanmem, choose yes. There was a bug within scanmem regarding this feature but it has been fixed now

If you prefer the AppImage binaries, a new version will be released soon

**Comment by korcankaraokcu** [comment]
New version is out
