### ISSUE TITLE
After setting and removing breakpoint on Sonic the Fighters via emulation w/RPCS3, the application still breaks every write

### ISSUE THREAD

**Issue by coatlessali** [korcankaraokcu/PINCE#270]
Environment to reproduce:
- Arch Linux
- Niri Scrolling Wayland Compositor
- xhost settings permitting root
- xwayland-satellite as xwayland implementation

Steps to reproduce:
- Open RPCS3's official AppImage.
- Launch the game "Sonic the Fighters".
- Pause the emulator when the ESRB logo appears in-game.
- Attach to the `rpcs3` process.
- Watch the memory region for address `0x3004AA62D` and set a break point for writes only.
- Press F7 to step.
- Remove the break point.
- Press F3 to run.
- Application will break even though there are no break points.

**Comment by korcankaraokcu** [comment]
Enable GDB Logging from Settings->Debug and then share the GDB log. This will tell us if GDB is having internal problems. Also share the console log starting from the breakpoint being set. This will tell us exceptions happening outside of GDB

Does this happen outside of RPCS3?

**Comment by korcankaraokcu** [comment]
> It was pausing on a bunch of SIGSEGVs

This happens with Java as well, known behavior. Check these pages for more info:
https://github.com/korcankaraokcu/PINCE/wiki/Java-games
https://github.com/korcankaraokcu/PINCE/wiki/PROCESS-IS-FREEZING-CONSTANTLY

> And after disabling them, there were no further issues

Should I be closing this issue then?

**Comment by coatlessali** [comment]
Absolutely. Sorry for the trouble. Have a pleasant day/evening.

Sent from Proton Mail Android

-------- Original Message --------
