### ISSUE TITLE
[Speed hack] (like in cheat engine)

### ISSUE THREAD

**Issue by Twig6943** [korcankaraokcu/PINCE#272]
any updates on this?

**Comment by Bloodiko** [comment]
This is neither productive not helpful. Please dont post such issues. 
It is on the todo list (see Readme), but very far away and not a priority. 

Unless you have an idea on how it can be implemented, such an issue especially with this question is not helpful.

**Comment by Twig6943** [comment]
Also what about an icon? ( https://github.com/ivan-hc/AM/issues/1019 )

**Comment by brkzlr** [comment]
Stick to one topic per issue and create issues if there are legitimate issues. For questions and other stuff, we have a Discord server.

Closing and locking.
