### ISSUE TITLE
Process automatically set breakpoint on attach

### ISSUE THREAD

**Issue by FatSquare** [korcankaraokcu/PINCE#274]
OS : Arch linux

after attaching Pince to the process to the game "Terraria"
The game freeze while trying to continue it keeps freezing with the the message on console

it seemed like was the game setting breakpoints automaticlly, can I maybe stop them ?
```
Last command: interpreter-exec mi "-break-list"
^done,BreakpointTable={nr_rows="0",nr_cols="6",hdr=[{width="7",alignment="-1",col_name="number",colhdr="Num"},{width="14",alignment="-1",col_name="type",colhdr="Type"},{width="4",alignment="-1",col_name="disp",colhdr="Disp"},{width="3",alignment="-1",col_name="enabled",colhdr="Enb"},{width="10",alignment="-1",col_name="addr",colhdr="Address"},{width="40",alignment="2",col_name="what",colhdr="What"}],body=[]}
^done
0.0005438327789306641
```

**Comment by FatSquare** [comment]
I was trying to edit the last post because I forgot to add description but it got closed it immediately, my bad

**Comment by brkzlr** [comment]
Did you even bother to follow the link I posted in the previous issue?

**Comment by FatSquare** [comment]
yes I did, and i dont see any signal being send. I event tried stop the signal SIGTRAP,SIGSEGV ( even tho the game is not made using java)

**Comment by brkzlr** [comment]
1. Make sure you're using either our AppImage or local dev build. Using the AUR package is not supported and we won't help at all with that.
2. Post the full terminal log here. That small bit you posted is completely useless and doesn't tell anything.

**Comment by korcankaraokcu** [comment]
@FatSquare `interpreter-exec mi "-break-list"` is used to get bp list, not set them. Brk is right, send the full log or else we can't tell anything. Also be sure that you are using the latest version of either local dev or AppImage

**Comment by FatSquare** [comment]
I was searching for any signal call but either that useless line i sent was the full ouput or I just didnt see anything else somehow. however after updating to the last AppImage it was clear that the game was calling every signal from 35 to 127 after turning them off. it's working now.

Thanks
