### ISSUE TITLE
AUR version not working

### ISSUE THREAD

**Issue by Qiu3344** [korcankaraokcu/PINCE#29]
When I am trying to launch pince(gksudo pince) I get this error:

`QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Detached from the process with PID:-1
Last command: source /root/PINCE_USER_FILES/gdbinit
 
&"source /tmp/PINCE-connection/-1/gdb_command.txt\n"
^done

0.004914045333862305
Traceback (most recent call last):
  File "PINCE.py", line 4085, in <module>
    window = MainForm()
  File "PINCE.py", line 284, in __init__
    self.about_widget = AboutWidgetForm()
  File "PINCE.py", line 1219, in __init__
    authors_text = open("AUTHORS").read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 32: ordinal not in range(128)`

Anybody knows a solution ?

**Comment by korcankaraokcu** [comment]
I'm on the vacation right now, will look into this issue when I'm back. @TsarFox is the AUR package maintainer, he can also look into this issue if he's available.

**Comment by TsarFox** [comment]
Which version of Python are you running? Also, could you please get me the output of running this in the Python REPL:
```python
>>> import sys
>>> sys.getdefaultencoding()
```

**Comment by Qiu3344** [comment]
On python2 it's 'ascii' and on python3 it's 'utf-8'

**Comment by TsarFox** [comment]
Thank you very much. It seems that the issue is that `python` in your $PATH points to the python2 binary. I've updated the PKGBUILD to explicitly invoke `python3` instead; can you confirm that that fixes the issue?

**Comment by Qiu3344** [comment]
yes! Thanks !

2017-07-17 22:38 GMT+01:00 Jakob Gn <notifications@github.com>:
