### ISSUE TITLE
Inferior crashes after a certain time once in a while upon injection of a never-ending thread

### ISSUE THREAD

**Issue by korcankaraokcu** [korcankaraokcu/PINCE#3]
It also crashes when superfluous number of threads get injected, which is quite normal to be honest but not desirable. Will try to write better threads asap.

**Comment by salihmarangoz** [comment]
In PINCE/Injection/AdditionalThreadInjection.c",

threadinf is a local variable, it is deallocates from memory when function ends. This may cause problems because first parameter of pthread_create() is address of threadinf.

Suggested Change:
```C
void injection()
{
	int *a=1;
	pthread_t *threadinf = (pthread_t*) malloc (sizeof(pthread_t));
	pthread_create(threadinf, NULL, infinite, (void*) a);
}
```

**Comment by korcankaraokcu** [comment]
That was a good one, tested on a few applications. After this [patch](https://github.com/korcankaraokcu/PINCE/commit/dfd8653eae5f94476e84c3a8d35d3b2180cc352e), the debuggee doesn't crash even after 20-25 thread injections. Might close this issue once I test this enough.
