### ISSUE TITLE
How can I setup .desktop file to run PINCE?

### ISSUE THREAD

**Issue by AkumaRRR** [korcankaraokcu/PINCE#30]
> [Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Name=pince
Exec=gksudo python3 /home/alex/Scrivania/Alex/PINCE/PINCE.py
StartupNotify=false
Terminal=false

This seems not to be the case. I'm only able to run the app from its directory by command line with gksudo python3 PINCE.py

**Comment by korcankaraokcu** [comment]
I'm on the vacation right now, will look into this issue when I'm back

**Comment by AkumaRRR** [comment]
ok, thanks!
Anyway, I'm using pince and it works like a charm. It needs a scan mem though.

**Comment by korcankaraokcu** [comment]
Scanmem/GameConqueror integration will be implemented at the very late stages of PINCE development, see **Roadmap** part of readme file for more information.

The reason behind this is that you can use scanmem and PINCE together already by using GDB Console. Check [here](https://github.com/korcankaraokcu/PINCE/wiki/Using-GameConqueror-with-PINCE) for instructions. It makes more sense to develop debugging part of the project right now, since scanmem doesn't have any debugging features and you can use scanmem with PINCE already.

**Comment by AkumaRRR** [comment]
Yep, that's exactly how I'm using it. It isn't pretty handy but, hey, it works well ^^
Another issue I noted it's I can't run it in background as usual from the shell. I have to use "nohup gksudo python3 PINCE.py &" to redirect the output

**Comment by korcankaraokcu** [comment]
@AkumaRRR Recently got back from the vacation, sorry for the delay. I've tried almost every possible sudo/gksu/gksudo parameter combination with my desktop file but had no luck so far. It becomes active for a moment, then closes itself. Wish I could at least get a log file that gives some information.

About another issue, what do you mean by running it in background, doesn't sudo/gksudo work properly? Also, what kind of error it gives? (if there's any)

**Comment by korcankaraokcu** [comment]
@AkumaRRR DID IT! It was soooooooo simple. All you have to do is to change current working directory to PINCE directory before executing. Try changing your exec parameter to something like this:

`cd /home/$user/PINCE && gksudo sudo python3 PINCE.py`

**Comment by korcankaraokcu** [comment]
Btw, this is the desktop file I've ended up with

```
#!/usr/bin/env xdg-open
[Desktop Entry]
Type=Application
Exec=cd /home/korcan/PINCE && gksu sudo python3 PINCE.py
MimeType=application;
Icon=
Terminal=false
Name=pince
GenericName=pince
Comment=pince
Categories=Qt;KDE;
```

**Comment by AkumaRRR** [comment]
Thanks!

About the other issue, if I run pince by shell I can't close the shell, even if I run it with
"gksudo python3 PINCE.py &" (it won't attach to any process)
I have to redirect the output in nohup.txt with
"nohup gksudo python3 PINCE.py &"

**Comment by korcankaraokcu** [comment]
Sorry but I can't reproduce the second issue. Using it by clicking to it just works fine for me in KDE
