### ISSUE TITLE
`thread_info_multiple_threads` fails to parse `gdb` output with `wine` processes

### ISSUE THREAD

**Issue by user202729** [korcankaraokcu/PINCE#37]
On my machine (gdb 8.1, Arch Linux, PINCE obtained from AUR), `gdb` output for `info threads` sometimes look like this: (when there are multiple threads)

```
* 1    LWP 7406 "winhlp32" 0xf7ffade9 in __kernel_vsyscall ()
```

That makes the regex `thread_info_multiple_threads` fail to parse the output.

Example invocation:

```
[user202729@archlinux ~]$ wine winhlp32 &
[1] 7406
[user202729@archlinux ~]$ sudo gdb
GNU gdb (GDB) 8.1
[[GDB copyright information and help...]]
(gdb) attach 7406
Attaching to process 7406
[New LWP 7408]
0xf7ffade9 in __kernel_vsyscall ()
(gdb) info threads
  Id   Target Id         Frame 
* 1    LWP 7406 "winhlp32" 0xf7ffade9 in __kernel_vsyscall ()
  2    LWP 7408 "winhlp32" 0xf7ffade9 in __kernel_vsyscall ()
```

This only happens with multithreaded processes started with `wine`, I have not experience a similar situation for non-Wine processes.

**Comment by korcankaraokcu** [comment]
Sorry for responding late, gmail stopped notifying me about github for some reason. [This commit](https://github.com/korcankaraokcu/PINCE/commit/ec0ba6b6f2adb671955cfd71b7c165c9a0913a3f) will probably fix your issue. Update the project and try again

**Comment by korcankaraokcu** [comment]
`thread_info_multiple_threads` now returns the entire matching line of the current thread. Since GDB's output is inconsistent, it's quite hard to satisfy all possible output formats. Here's the patch: https://github.com/korcankaraokcu/PINCE/commit/3228bc125ba2fc1132fd3c422116414b848e5fd5
