### ISSUE TITLE
Pycharm gives "parameter self unfilled" warning about a lot of PyQt related functions

### ISSUE THREAD

**Issue by korcankaraokcu** [korcankaraokcu/PINCE#4]
The functions are not related to each other. This issue also doesn't prevent PINCE from working, so this one isn't really a bug, since PINCE can work flawlessly under these warnings. But I'd really like to know what's going on at the background.

**Comment by SunyataZero** [comment]
Hi, i found this issue while googling after having the same problem. This doesn't answer your question but cound be useful: You can use "# noinspection PyArgumentList" above the init function (for example) which tells PyCharm to not warn for this kind of thing. More info here: https://www.jetbrains.com/help/pycharm/2016.3/suppressing-inspections.html
Hope this helps!
Kind Regards, Tord

**Comment by korcankaraokcu** [comment]
Sorry for taking this much time to reply to your post. I completely forgot that I've opened this issue. Thanks for your suggestion, but I'd not like to ignore a real PyArgumentList error just because of this issue. I've got used to ignore those warnings by eye anyway 😄 I'll leave this issue open for other people to see and share their thoughts.

Thanks for the reply, have a good day.

**Comment by ShrekerNil** [comment]
Any one got this problem solved ??? Thanks!

**Comment by korcankaraokcu** [comment]
@ShrekerNil Not yet unfortunately

**Comment by MrSeile** [comment]
I'm having the same problem. Is there any way to fix it without completely removing all inspections?

**Comment by Me817** [comment]
I'm having the same problem and found nothing. I used the ignore statements but I would rather like do solve this warning. Does anybody have found a solution?
Thank you in advance.

**Comment by korcankaraokcu** [comment]
Good solutions were presented and I'm no longer using PyCharm, closing the issue
