### ISSUE TITLE
Disassemble view scrolling

### ISSUE THREAD

**Issue by user202729** [korcankaraokcu/PINCE#44]
(this is just an [enhancement]. But I find it very annoying)

Some issues:

* Because the disassemble view updates when the scroll bar changes value, it's impossible to scroll the disassemble view using the keyboard. (except by using goto, which is not easy)
* After scrolling, it's necessary to pull the scroll bar to the middle position.

I'm thinking of implementing it like [this](https://tio.run/##rVdtT9tIEP7c/Io9UIUNwQ1tuQ9Vc1KhHEUn2qb0ygeEosUeJ6uzd63dDcFX3W/nZnbXLzFUh6pDKLFndt5nnp1UtV0q@er@PteqZJ/rmT1MZvZ0JZgoK6Xt7miDcSmyBVjzOPNYaWg5/puZ2oxGacGNYef1sZJWq6IA/Wb0bJulSkpILbNLYZhV7PT9EVOaGVUCkuRiNHqWQc4qDbdznmUajIkMFPmYhbcY1TzTYFdaNqS98P381f6rIC/hzv6EfJBOldbo5NMVRK2G6XQSBy2ZMJgCKG8KeETDzs4Ofp6KW0A1kglpYQGaRUIyDbxAHzLwWVqLomA34FIFdxVpEErGrReGcVYIY1HWguZoLmYqZ2aV5yIVIG1Rs5LLmjVsk6BsBDxdMiigxBM@YlMpmbmqcKbVOm69rDS618RIZJXnBiybssOJc8OsCnq7usa3kHqN70ECieulKIC1rLcNi@0xr4tSEhQlvKpAZlFkrI4akXic75TqlgG/G39viM8PJpN/dmLyqG@Wkp1sdECrpSudtzUajT7Ov3y6RKmDye7ur2ybksn1Ap1dlTegu0Y@x4IU0ezdDbrFU/uVMuloVE6q93wupLDzeSh22jb@mFVcU5an7KOS4MpvVhXoKGgdO5fjpNXgz5O3LpZOFaroXhr2QlkVvZ7QX9N7jvSw6Xwh851TZLPvgYMZRFZTkJC@zkoynIZeH7ijxnJt59gwIb7O6xLbLjMDcmeoaw/HyLjlx0suF5AlUAobUVkdR8gM7qLJmE3i8YDoqrd/MG68LlalPFYrjDLePyAXYyqpMasSGNyCrh3KsDTYYTmBD@JWgaNi6ySkD4PxSnwK2/LNXLnOnOW4DwTOjRY9OieeKv@ywQzMQRBy8Y3RFRwclLTJe2GqgtdfkOBERe6Zvwy5YZac4tk3rgWndIzImiuS05zgsydudNeg@CNvRyrLNmr6pi1Dv/r42dJ71e/10hATk14zQYGWBjp/I53OGBVqzggdqXLR4Ny@Ayx3cNhlPesPbpW@@f8/HOMr4bFvoH2PFSCjDdUxezttwx16s4cA9R/RPbjzNqL7uTC6Dt0Qv/I53/Tx@so3lu//KL7usPObgHU0c5BJjz9AzNJjoZ@W6QAqf4yOeHt4bHbyzueG/g20FSkvLlKK9IjrzwoHvY5wXlrSu2LNa/Mpz/sKL/BiTC1es6S5A/0zCyUFkFwgiBTQnnpU9AiW/FYo/Zi4O/NFrU1f8iQT9qsWC9wDzCNCH1X/QCt4G2L8ADxzeVoKdLlLAxYS7Ny4cIkcEK5PdbcPpXqbnSHwcgt@Jckp4eCWi6G1Nn1okBLNixV4MH7x4mUvqBBnj@Xt/wX1Z2qxE9x/GphsYQ0SZEcxTTuV6g@o5x9wQRyz8HIiMz/rs3NUwRdwpO6SNdcSqxJ0bV361y18/NOAuxBZVQA3sNWCTWNnOm00nzq1rpEaMHQvkZuhqzAXeNus0hQfrgmZz2S1su8FL9QiwUX5rI3Hjd0W3bXkxQlueLq587ZCt2@M6DbhLC19POzH@E/Ia5eA@x8ueAYnizoLL3XjBaJNLSThTy@EpPDbPQsXQmJUmKwgibCECyAKYKm5vhHYbLoOWw8zhVgsaXE0JXc3AzolvSCpwbZc4Y7ad56w2yfF45d3zO0hD2Fo2JM9tGymfbNBoNc3N4rr7AK4Tpch0ca9@A0HAafFHS7k70qX0YyeLhGd1I@gZxdXPvM42nhWb5rE3xAdTnAbOfT71iM7Wv9nT9TKNm3V7JIDufacJZx05xxudrJhT9w4R9N3CvTzSdduRRqz1xP/0Q77k4atG4ITk/IKuis@LZSBKH5alXB5p6F4V9FKxalbI/w9mGASb@PR2tWAQmtK09ASs3T7CIoncAfpnNri/v5f) instead. Thoughts?

(this may disassemble up to once per scroll, which may cause bad performance. It's possible to do better)

`HexView` and `AsciiView` can use a similar approach. (or easier, because the steps are known, so just make it have about `2**64//column_width` rows)

**Comment by korcankaraokcu** [comment]
>it's impossible to scroll the disassemble view using the keyboard

You can use tableWidget_Disassemble_key_press_event to detect up&down keypresses and use tableWidget's viewPort to detect visible rows. The rest is simple logic.

While I agree on the part tableWidget_Disassemble should be based on a custom tableView instead of a tableWidget, converting a tableWidget with many functionalities into a tableView just for implementing one simple feature would take too much time. I can implement the scrolling feature with the current tableWidget if you want. You also can implement the idea in your mind if you think it's not that much time consuming. Waiting for your call

**Comment by user202729** [comment]
I didn't try to implement it, I'm not sure how much time it would take.

However, I think that using a `tableView` will make the code simpler than using a `tableWidget`, then reimplement handling for ↑, ↓, PgUp, PgDn, Home, End, and also the timer for listening to the scroll bar.

I may try to implement it later.

**Comment by korcankaraokcu** [comment]
I've implemented this feature with the current `tableWidget`, check `disassemble_check_viewport` function for details. I won't close this issue yet because the real solution is to use `tableView` instead of a `tableWidget`, just like you suggested

**Comment by neoh4x0r** [comment]
@korcankaraokcu I believe this issue might be addressed byt the pyqt6 port that's in the works  by N00byKing (#142), coupled with the PR I posted against it (https://github.com/N00byKing/PINCE/pull/1).

The only thing I didn't implement was Home/End in Dissassembly/HexView (but PageUp/Down works). Also a timer isn't really necessary for scrolling (I believe it was causing it to get stuck in an endless scrolling loop).

Just using the sliderChange event, as I did in the updated PR, should be enough to make the components scroll up/down (and have the slider return to the middle point). To make them scroll programmatically  you just call the setValue method of the scrollbar and use a positive or negative scroll amount. I also used a flag (in the sliderChange event method) to indicate that a scroll operation was being performed, and any new scroll requests would be blocked until the current scroll operation was complete.

PS: Both PRs are still in draft mode, but I suspect if/when they are finished, and merged, that it would resolve this issue.

**Comment by korcankaraokcu** [comment]
This has been implemented by @neoh4x0r within the recent pyqt6 patch. Thanks for the contribution, much appreciated. Also about using `tableView`, I guess it's not critical as much as the feature itself. It can be addressed later on if needed, closing this issue for now
