### ISSUE TITLE
Nested fields in AddressTable

### ISSUE THREAD

**Issue by user202729** [korcankaraokcu/PINCE#46]
[enhancement].

This can be useful if multiple addressed is dependent on a common pointer.

Child fields may refer to parent's field by using an expression, `%`, for example.

Alternatively, Cheat Engine's approach is to append the child address to the parent address if it makes sense. (for example if parent address is `0x123455` and child address is `+1` then the computed address for child field is `0x123456`)

**Comment by user202729** [comment]
I'm implementing this, using an `QTreeWidget`.

https://github.com/user202729/PINCE/tree/nested-adrtable

Because `QTreeWidget` are very different from `QTableWidget`, there may still be a lot of bugs in the code. Also, structured copy/paste are not supported. (copy and paste a structure will flatten it)

Also, there are currently no way to make children address dependent on parent address.

**Comment by korcankaraokcu** [comment]
Resurrection time. This issue was only half done since we have nested address table but no parent-child pointer association. It was closed automatically by the PR by mistake. Reopened for the implementation of the pointer association

**Comment by korcankaraokcu** [comment]
Implemented by https://github.com/korcankaraokcu/PINCE/commit/2ce8f43ca2b51b17c45391dfcebfe2d1f16ae820
