### ISSUE TITLE
Stop tracking watchpoint freezes PINCE

### ISSUE THREAD

**Issue by user202729** [korcankaraokcu/PINCE#53]
This is a GDB bug.

[GDB's `-break-list` can produce non MI compliant output](https://sourceware.org/bugzilla/show_bug.cgi?id=9659). That can freeze pygdbmi.

`-break-list` is executed when [`delete_breakpoint` is called inside `pushButton_Stop_clicked` of the trackpoint widget](https://github.com/korcankaraokcu/PINCE/blob/master/PINCE.py#L3140), which calls `check_address_in_breakpoints` which calls `get_breakpoint_info`.

**Comment by korcankaraokcu** [comment]
This issue has been fixed in https://github.com/korcankaraokcu/PINCE/commit/375f7afae527572156b6c2018db74137974d2db7. But I'll keep it open since the fix is temporary and somewhat ugly. This issue should only be closed if gdb fixes it

**Comment by korcankaraokcu** [comment]
GDB fixed this bug in newer MI versions and decided to not update the default version we are using right now to avoid breaking old projects. So, the temporary fix is here to stay. It can be changed if we somehow be forced to use newer MI versions. Here's the discussion in Bugzilla:

https://sourceware.org/bugzilla/show_bug.cgi?id=9659

Closing this issue for now as there's currently nothing to do.
