### ISSUE TITLE
Problems while executing a command as user

### ISSUE THREAD

**Issue by korcankaraokcu** [korcankaraokcu/PINCE#61]
Despite `SysUtils.execute_shell_command_as_user` working properly for web browsers, some other GUI applications such as file browsers and text editors might show buggy behavior. For instance, some standard KDE applications such as **Dolphin** and **Kate** are [unable to show user icons](https://bugs.kde.org/show_bug.cgi?id=353263) even while invoked within `sudo -u non_sudo_user`. I've also tried invoking **Kate** with `subprocess` module with user demotion and all `os.setuid` and `os.setgid` variants, nothing has worked.

The first solution that came to my mind was to change `PINCE.sh` in a way that it creates a user bash session before invoking PINCE so PINCE can communicate with it via IPC and invoke commands on demand. But this looks a bit hacky, doesn't it? I'm sure that there's a more convenient way to solve this. Open for ideas

**[Enhancement]:** Solving this issue can allow `LogFileWidget` to have its own buttons to show files via file browsers or text editors

**Comment by TsarFox** [comment]
As in, the KDE icons and such? Which widget toolkits do work? It's possible that there's a discrepancy between the theme configuration for root and the theme configuration for the unprivileged user - have you tried, in addition to `os.setuid` and `os.setgid`, changing `$HOME`?

**Comment by korcankaraokcu** [comment]
import subprocess
    env = dict(os.environ, HOME=get_user_home_dir())
    subprocess.call("sudo -u '#" + uid + "' " + command, env=env, shell=True)
Tried changing `$HOME` with the code above but it didn't work. I also tried to preserve the environment variables by using the `-E` parameter but it also didn't work
>It's possible that there's a discrepancy between the theme configuration for root and the theme configuration for the unprivileged user

You were right, it's reading the `XDG_RUNTIME_DIR` env variable and the variable is apparently set to `/tmp/runtime-root` if you invoke the command as root. I've tried setting it to `/run/user/1000` manually in runtime by modifying env but it still prints the error **`QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'`**
>As in, the KDE icons and such? Which widget toolkits do work?

It looks like this:
![image](https://user-images.githubusercontent.com/5638719/46374980-d8d68200-c69a-11e8-9737-acc736c631cc.png)

**Comment by TsarFox** [comment]
Hm. Does it work with kdesudo? If it does, you could look through [their code](https://bazaar.launchpad.net/~kubuntu-kdesudo/kdesudo/trunk-kde4/files/head:/kdesudo/) and start reimplementing the setup/teardown in PINCE.

**Comment by korcankaraokcu** [comment]
Apparently running `kdesudo -u user_name -c "KDE_SESSION_VERSION=5 KDE_FULL_SESSION=true  dbus-launch dolphin file_path` works but if I let the `xdg-open` handle the file manager, it fails. Can't rely on dolphin since not everyone have to use it as the file manager

One solution that comes into my mind is to get the file type by invoking `xdg-mime query filetype` and then get the default application for that type by invoking `xdg-mime query default` which returns something like **`org.kde.dolphin.desktop`**. That could be parsed to find the application we need to run. Again, this sounds a bit hacky as well. Also, this problem didn't exist in Qt4, it only exists in Qt5. So, I'll wait for KDE to fix this. If they didn't as we get close to the first version of this project, I'll implement the solution above.

Btw, does `SysUtils.execute_shell_command_as_user("xdg-open /home/")` work properly for you?

**Comment by TsarFox** [comment]
Nope. Doesn't work with Dolphin, and doesn't work with Caja.

**Comment by korcankaraokcu** [comment]
I've upgraded my Kubuntu version to 18.04.1 and PINCE now gives **`QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'`** error on start. It still works tho

**Comment by awsdert** [comment]
Dunno if this will fix this particular issue as I didn't read thoroughly but as far as permissions go PINCE can get hold of them like Game Conqueror at boot of app with the help of this code:
`sprintf(cmd,"/bin/pkexec %s/%s", getenv("PWD"), child );`
Basically the launched PINCE executable should behave as a launcher and launch the GUI in a child process, I know this method works because I've already done it myself while making a custom trainer for Final Fantasy XV while on manjaro, I've read a mention of polkit or something when I was looking for that GUI prompt method so I could quick compile and run from within Geany (BTW that code is in C), I went with pkexec because it's simpler and works on my system (Manjaro - arch based distro)

**Comment by awsdert** [comment]
Scrap pkexec, found gksu was installed by default and that doesn't block GUIs, I initially didn't try it cause I thought it only came with gnome but I stand corrected, also it's sufficient to just shove it in a normal launcher, although if one is going for both command line & GUI I would try sudo first then gksu on fail before aborting altogether.

**Comment by korcankaraokcu** [comment]
I cannot replicate this issue anymore, closing
