### ISSUE TITLE
Any chance of a deb or snap package for ubuntu?

### ISSUE THREAD

**Issue by nitrocode** [korcankaraokcu/PINCE#63]
Hi. Just wondering if there is a deb or snap package for ubuntu on the roadmap.

Great project by the way!

**Comment by korcankaraokcu** [comment]
Packaging will be done when the project reaches its first version, which is 0.1.0. You can use the install.sh script till then

Thanks!

**Comment by nitrocode** [comment]
@korcankaraokcu could you create a milestone for 0.1.0? I'd love to track it :)

**Comment by korcankaraokcu** [comment]
@nitrocode Sure thing, created it
