### ISSUE TITLE
Cannot do First Scan

### ISSUE THREAD

**Issue by nitrocode** [korcankaraokcu/PINCE#64]
I installed the linux game Pingus and attach to the process. Once I do, it says 

> 29001 - pingus  [stopped]

and the entire window is greyed out and I cannot First Scan or Next Scan. Is there something I need to do to enable searching?

**Comment by korcankaraokcu** [comment]
Unfortunately, scanning isn't implemented yet, those buttons are just placeholders. I'm planning to finish debugging features first. You can use GameConqueror/scanmem for memory scanning for now, check the associated [wiki page](https://github.com/korcankaraokcu/PINCE/wiki/Using-GameConqueror-with-PINCE) for instructions

The reason behind this is that there might be new features and refactorings in scanmem and if I combine the scanmem with PINCE now, I'll definitely need to adjust later on. So, I'll finish scanmem-independent features first, then the scanmem integration. You can already use scanmem&PINCE without losing your debugging session anyway, it's a bit annoying, but useable 😄

**Comment by korcankaraokcu** [comment]
Also, if you wonder why I've bothered with the placeholder buttons, it'll look exactly like that at the end when the scanmem gets integrated and it gives me morale to see the future of the project whenever I launch it

Btw, most used debugging features such as **dissect code**, **trace instructions**, **what accesses this address**, **conditional breakpoints&watchpoints** and many more are already implemented. So, you'll feel right at home for a basic debugging session, have fun ❤️
