### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by awsdert** [korcankaraokcu/PINCE#65]
Because the installation insists on gdb 8.2 while my system reports it already has the latest version and refuses to install which causes the whole script to bail outright, please just set your install script to require min gdb 8.2 instead of insisting on that exact version

**Comment by awsdert** [comment]
it also shows up a long list of permission denieds when it's trying to change ownership, I've already tried running it with sudo both in normal terminal and root terminal, no luck

**Comment by korcankaraokcu** [comment]
PINCE compiles&installs gdb to currently active directory, it doesn't mess with system packages. Could you share the exact error log you got while installing? Also, what's your OS?

**Comment by awsdert** [comment]
I recommend just dragging the scrollbar with the mouse once you get to the permission denied stuff and going right to the bottom and scrolling back up to the point the permission denied stuff ends as there is a lot

**Comment by korcankaraokcu** [comment]
That's very weird indeed. Did you try any folder other than `/media/`? Maybe it's something related to the filesystem of the mounted folder

**Comment by awsdert** [comment]
It's btrfs, I don't expect there to be filesystem issues in the first place, but I'll try anyway

**Comment by awsdert** [comment]
correction, was fat32, just installed gparted to check before I try

**Comment by awsdert** [comment]
Well that made a difference, getting different result now, it asked for my password and is doing some s**t now

**Comment by awsdert** [comment]
k 1st problem I noticed so far is that when it attempted to compile infrun.c came up with errors, I'll update my copy of pince source code once it finishes and run again

**Comment by awsdert** [comment]
also problems in ui-out.h

**Comment by awsdert** [comment]
and record-btrace.c

**Comment by awsdert** [comment]
alright! it successfully installed! I will point out that the window should be resizable and have a smaller default size, I can't see the bottom with my 1280x720 resolution (native projector resolution)

**Comment by korcankaraokcu** [comment]
Noted, will look into it when I find some free time, should be trivial

**Comment by awsdert** [comment]
thx :)

**Comment by korcankaraokcu** [comment]
Smaller default size makes it look weird and unnecessarily compact but I agree on the fact that it should be resizable so I patched it that way: https://github.com/korcankaraokcu/PINCE/commit/af4f8eadb1f97db4a78653b20054c2c209bad555

Just run `git pull` in the root folder, no need to reinstall PINCE

**Comment by awsdert** [comment]
ohh that'MUCH better :D Thank youu! :)

**Comment by awsdert** [comment]
One thing to note however, when you said to just run git pull you forgot that tracking information needs to be set 1st, thankfully git was helpful enough to give an example command, I simply replaced <branch> with master

**Comment by awsdert** [comment]
&lt;branch&gt; was supposed to be in there, didn't realise git would replace that
