### ISSUE TITLE
Python is not user friendly

### ISSUE THREAD

**Issue by awsdert** [korcankaraokcu/PINCE#68]
What I mean by this is that the typical user won't understand how to get python compiling or even setup for their system (I myself struggle to get it compiling everytime I try)

It would be better to use an open framework like IUP which is easy to compile as it follows the same rules as Lua (to the extent that is possible for APIs that wrap around the system API) so one can simply run "make" in the directory of the makefile, the API is simple to use too, I favour it every time I want to use GUI functions in my own projects. Not to say you can't use alternatives like wxWidgets or hook into the python library and manually create the GUI but IUP does have Lua support built into it so you could just call IUP functions under the hood when replicating CE GUI functions and not bother manually mapping GUI functions in C or Python.

**Comment by korcankaraokcu** [comment]
Python is installed by default on many distributions. If your distro makes it hard to compile/install python, you should blame your distro, not the python itself.

>Not to say you can't use alternatives like wxWidgets
I dont want to? I dont see anything wrong with using PyQT as a GUI library. Everything is written with python in this project, from GUI to GDB scripts. I just dont see any need to use another language when every single component is already scriptable.

Closing this issue as it contributes nothing to the project, sorry.
