### ISSUE TITLE
Suggested default icon until you make a logo

### ISSUE THREAD

**Issue by awsdert** [korcankaraokcu/PINCE#70]
I found one in my pre-installed icons (on manjaro) called custom-toolbox, I think that would be a suitable icon for time being, as for future logo I think a joypad with a wrench on top would make for a good logo since this is focused on cheating, if you want a more general suggestion then the only thing that comes to mind is similar but with a gear instead of a joypad

**Comment by korcankaraokcu** [comment]
But PINCE already has a logo:
https://github.com/korcankaraokcu/PINCE/blob/master/media/logo/ozgurozbek/pince_small.png

We also have a big variant but it's not used yet:
https://github.com/korcankaraokcu/PINCE/blob/master/media/logo/ozgurozbek/pince_big.png

**Comment by awsdert** [comment]
huh, I wonder why bauh didn't include it when I installed it then?

**Comment by awsdert** [comment]
Had a chance to search for it just now and it seems it was included but doesn't show in the icons dialogue when I tried to create a launcher (since none was created automatically). There is a problem with the icon however in that from what I've seen in nemo the icon doesn't have a background making it unsuitable for my dark desktop theme, I suggest a simple light blue filled rounded square starting from outside the black square, that would make it suitable for both dark and light themes

**Comment by korcankaraokcu** [comment]
Got new logos thanks to #71, I'll implement a dropdown menu to select them asap

**Comment by korcankaraokcu** [comment]
There you go, tell me what you think. With this new feature, you can also add your own logos. Just throw them into the media/logo folder

**Comment by awsdert** [comment]
Sorry for late reply, been busy with things and forgot, yeah love the new option, I just can't see the logo on my taskbar and menu cause I gotta go through terminal to use my password, have you added an call to the system prompt for that yet?

**Comment by korcankaraokcu** [comment]
Ah, forgot to tell, you can use Settings->General menu to choose whatever icon you want to use. The logo should also appear in the taskbar after you choose it via Settings menu. Let me know if it worked

**Comment by awsdert** [comment]
Nah, but I think that's because the icon is tied to the launcher atm, if I ran pince via terminal it probably would however I don't wish to open the terminal every time I want to start pince

**Comment by korcankaraokcu** [comment]
```
[Desktop Entry]
Version=0.1
Name=PINCE
Comment=Game hacking tool
Exec=sudo python3 /home/korcan/PINCE/PINCE.py
Icon=/home/korcan/PINCE/media/logo/ozgurozbek/pince_small_transparent.png
Path=/home/korcan/PINCE/
Terminal=true
Type=Application
Categories=Utility;Application;Development;Debugger
```
Would something like the above be sufficient for your needs? You can ignore the `/home/korcan` part, it can be automatically replaced with the user path on the run.

**Comment by awsdert** [comment]
That still runs via the terminal, for now I've taken to developing my own substitute cheat app, I've gotten as far as opening /proc/<pid>/mem with read/write permissions (had to use gksu to avoid terminal, now using /bin/zenity --password > /bin/sudo $(PWD)cheat.AppImage when generating my launcher

**Comment by korcankaraokcu** [comment]
I thought the purpose of desktop entries were to offer a convenient way to launch applications. The solution above does exactly that. The terminal is executed automatically, just for you to enter your pass. So it removes the necessity of opening a terminal manually. I fail to see what's the problem in here.

**Comment by awsdert** [comment]
Because the terminal stays open until pince closes, I much prefer the GameConqueror way of opening where a one time prompt is given

**Comment by awsdert** [comment]
Since this topic is pretty much irrelevant to me now I've got my own app working I might as well close this issue, for peops who are impatient about PINCE you can download, compile and customize my one as a stop gap measure, unlike GameConqueror you're not restrained to single address records, you just have to implement the gui scripts for it assuming I don't get round to it myself
https://github.com/awsdert/gasp
Just be warned I have no intention of developing the GUI and backend to be as advanced as PINCE so it may be better to use side by side, also I'm not finished optimizing backend functions so be prepared for the rougher functions like aobscan to change the type of values they return,
also need a scanning interface still so gasp is currently only good for static addresses for now
