### ISSUE TITLE
dynamic library injection fails 

### ISSUE THREAD

**Issue by totalbajor** [korcankaraokcu/PINCE#72]
error:

(gdb) 
&"source /dev/shm/PINCE-connection/12644/gdb_command.txt\n"
&"/dev/shm/PINCE-connection/12644/gdb_command.txt:1: Error in sourced command file:\n"
&"No symbol table is loaded.  Use the "file" command.\n"
^error,msg="/dev/shm/PINCE-connection/12644/gdb_command.txt:1: Error in sourced command file:\nNo symbol table is loaded.  Use the "file" command."
(gdb) 
&"source /dev/shm/PINCE-connection/12644/gdb_command.txt\n"
&"/dev/shm/PINCE-connection/12644/gdb_command.txt:1: Error in sourced command file:\n"
&"'libc_dlopen_mode' has unknown return type; cast the call to its declared return type\n"
^error,msg="/dev/shm/PINCE-connection/12644/gdb_command.txt:1: Error in sourced command file:\n'libc_dlopen_mode' has unknown return type; cast the call to its declared return type"
(gdb)

gdb version:
-->show version
~"GNU gdb (GDB) 8.2\n"
~"Copyright (C) 2018 Free Software Foundation, Inc.\n"
~"License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law."
~"\nType "show copying" and "show warranty" for details.\n"
~"This GDB was configured as "x86_64-pc-linux-gnu".\n"
~"Type "show configuration" for configuration details.\n"
~"For bug reporting instructions, please see:\n"
~"http://www.gnu.org/software/gdb/bugs/.\n"
~"Find the GDB manual and other documentation resources online at:\n    http://www.gnu.org/software/gdb/documentation/."
~"\n\n"
~"For help, type "help".\n"
~"Type "apropos word" to search for commands related to "word".\n"
^done

the actual code I'm trying to inject:

```
#include "stdlib.h"
#include "stdio.h"
#include "string.h"
#include <unistd.h>

static void init(void) __attribute__((constructor));

static long custpow(long x, long y){
    long rez = x;
    if (y == 0 ) return 1;
    for(int i = 0; i < y -1; i++){
        rez*=x;
    }

    return rez;
}

static long xtoi(char * hex){

        int val, len;
    len = 0;
    long decimal = 0;

    len = strlen(hex) -1;

    for(int i=0; hex[i]!='\0'; i++)
    {
 
        /* Find the decimal representation of hex[i] */
        if(hex[i]>='0' && hex[i]<='9')
        {
            val = hex[i] - 48;
            //printf("%d\n", val); 
        }
        else if(hex[i]>='a' && hex[i]<='f')
        {
            val = hex[i] - 97 + 10;
            //printf("%d\n", val);
        }
        else if(hex[i]>='A' && hex[i]<='F')
        {
            val = hex[i] - 65 + 10;
        }
        long pw = custpow(16, len);
        long geo = (long)val * pw;
        decimal += geo;
        //printf("--%ld %d\n geo %ld %ld---\n", pw, len, geo, decimal);
        
        len--;
    }
    return decimal;
}

static void init(void){
    FILE *fp;
    FILE *fp1;
    printf("loading...\n");
    char address[500];
    fp = fopen("/home/arturas/addr.txt", "r");
    fp1 = fopen("/home/arturas/addr1.txt", "w");
    fscanf(fp, "%s", address);
    printf("%s\n", address);
    long addrlong = xtoi(address);
    //long * addrpoint = (long*)addrlong;
    printf("%ld\n", addrlong);
    fputs(address, fp1);
    fclose(fp);
    fclose(fp1);
    //printf("addr: %p | value: %ld\n", addrpoint, *addrpoint);
}
```

**Comment by korcankaraokcu** [comment]
Converting the return value to `(char *)` fixes this problem. I also updated the GDB version, so you should run install.sh after updating the PINCE
