### ISSUE TITLE
Allocate memory / Change Protection / Codecaves?

### ISSUE THREAD

**Issue by Symbai** [korcankaraokcu/PINCE#73]
How can I allocate memory or change protection of a memory region using PINCE for creating a code injection?!

**Comment by XutaxKamay** [comment]
I think you can use PINCE's GDB console in order to do these things, (call (void*)mmap(args...), call (int)mprotect(args...) etc)

Code caves are planned I guess.

**Comment by korcankaraokcu** [comment]
@XutaxKamay Well said, pretty much summed everything I was going to say. The automation of code cave injection is a planned feature. Therefore I'm closing this issue.

**Comment by Symbai** [comment]
What the correct gdb console command to remotely allocate memory?

`gdb call (void*)mmap(0,0x1000,7,0x22,-1,0)`

does nothing. Expected it to return the address for a 4096 bytes (size) read/write/execute, private / anonymous, allocation.

**Comment by XutaxKamay** [comment]
![image](https://user-images.githubusercontent.com/20893801/75346747-ab95ff80-589f-11ea-94a2-eb5c8384e376.png)
0x7fe86acae000
What do you mean by it does nothing?

**Comment by Symbai** [comment]
For me it simply hung after I entered the command, there was no return value. I've tried now again by restarting the game and it works now.

However it seems to ignore a provided desired location. I.e. when I enter:
`call (void*)mmap(0xa3a3000,0x1000,7,0x22,-1,0)`
it returns
`0xf3006000`
when I leave it to zero `call (void*)mmap(0,0x1000,7,0x22,-1,0)`
it returns
`0xf3007000`

Page alignment is 0x1000 on my machine and there is enough free memory nearby.
![Screenshot from 2020-02-26 14-33-29](https://user-images.githubusercontent.com/14368203/75349422-0bdb7000-58a5-11ea-9aae-780abce24505.png)

Am I doing something wrong? How can I be sure it allocates nearby (at least guaranteed within 2GB range so I dont have to long jmp to my codecave)

**Comment by XutaxKamay** [comment]
I do not see anything wrong though, if it returns this memory address it is because the os can't allocate at this memory place. Try to look better on what gives VM Start and VM End
0x804000 -> 0xa3a2000
0xa3a2000 -> 0xa3a3000
0xa3a3000 -> 0xa541000

Which means that you can't allocate memory 0x804000 to 0xa541000.

**Comment by Symbai** [comment]
It is 64bit OS and game, that's the issue. Why doesn't the system takes 0xa541000 as nearby? Because after 0xa541000 and 0xbe71000 there is nothing allocated?!

**Comment by XutaxKamay** [comment]
Oh yeah I didn't notice the addresses after, my bad.
I think it is because of performance issues mainly it always tries to allocate based on the last address that was allocated to. I'm not sure maybe going into kernel internals might give you a reply.

Well as you used to do just find an aligned address (0xa542000) and it should be fine?

**Comment by Symbai** [comment]
Figured it out. It works when:

1. MAP_32BIT is provided
2. I have to specifically set a nearby address which is located BEFORE the target address. I.e. in my example the target address module starts at 0x804000. Then I have to specify 0x800000 (and consider this is unallocated memory). When I instead specify 0x804000 or higher, it gives me an address in high range. It appears the underlying Linux function looks up but not down when trying to allocate for some reason.
