### ISSUE TITLE
Program freezes when selected in PINCE

### ISSUE THREAD

**Issue by NinjaPaimen** [korcankaraokcu/PINCE#74]
Title says it. When I select a process from the process list, it selects it, the process freezes (not PINCE) and it says <name of the process>(stopped)

using Linux Mint.

**Comment by korcankaraokcu** [comment]
That's the intented behaviour. GDB needs to stop the process in order to execute commands.

https://github.com/korcankaraokcu/PINCE/wiki/Working-logic-of-PINCE
