### ISSUE TITLE
Writing to process

### ISSUE THREAD

**Issue by vikke1234** [korcankaraokcu/PINCE#77]
Writing to a process from the saved addresses tree widget currently a little buggy, it works but it has the problem that GDB_Engine.examine_expression is called; and when you try writing to a process while it runs it throws an error.

Buuut, the function still works and it still writes but could have some side effects when trying to write to some nice expression (https://github.com/korcankaraokcu/PINCE/wiki/About-GDB-Expressions)

**Comment by korcankaraokcu** [comment]
With the latest patches, this issue doesn't seem to occur again, closing for now. Can be reopened if it occurs again.
