### ISSUE TITLE
ModuleNotFoundError: No module named 'libPINCE.libscanmem'

### ISSUE THREAD

**Issue by olanelson85** [korcankaraokcu/PINCE#82]
After using the [automatic install](https://github.com/korcankaraokcu/PINCE#installing-automatically), running `sh PINCE.sh` returns this error:
```
sh PINCE.sh
Traceback (most recent call last):
  File "PINCE.py", line 32, in <module>
    from libPINCE.libscanmem.scanmem import Scanmem
ModuleNotFoundError: No module named 'libPINCE.libscanmem'
```
Any idea on how to fix it?

**Comment by olanelson85** [comment]
Nevermind, a clean install fixed it.

**Comment by korcankaraokcu** [comment]
@olanelson85 Sorry about being late, glad that reinstalling fixed your issue. For the future reference, please add more details such as error logs you've encountered while executing the `install_pince.sh`
