### ISSUE TITLE
Fails to compile on Fedora 32

### ISSUE THREAD

**Issue by ghost** [korcankaraokcu/PINCE#84]
It's all there. It's just broke.

![Screenshot from 2020-07-13 20-20-29](https://user-images.githubusercontent.com/26858841/87366281-50129880-c546-11ea-8fda-941ec63960e8.png)
![Screenshot from 2020-07-13 20-21-10](https://user-images.githubusercontent.com/26858841/87366318-66205900-c546-11ea-9a4c-7288ea36b38d.png)
![Screenshot from 2020-07-13 20-21-38](https://user-images.githubusercontent.com/26858841/87366345-79cbbf80-c546-11ea-8785-c051812a7076.png)

**Comment by korcankaraokcu** [comment]
This isn't an error I've faced before. I also never used Fedora

- https://stackoverflow.com/questions/10792844/python-missing-or-unusable-error-while-cross-compiling-gdb
- https://github.com/crosstool-ng/crosstool-ng/issues/872

From what I read from the answers, you might need to install `python-dev` package. Try the solutions above and tell me if it works. If it doesn't, I can try to install Fedora when I find some free time.

**Comment by paulmenzel** [comment]
@ghost, did installing the package *python-dev* solve the issue?

**Comment by korcankaraokcu** [comment]
Installing `python-devel` with `yum` solves this issue, just tried on a fresh Fedora installation. You also might need to install `gcc-c++` package.
