### ISSUE TITLE
ModuleNotFoundError: No module named 'libPINCE.libscanmem'

### ISSUE THREAD

**Issue by philenko** [korcankaraokcu/PINCE#86]
Ubuntu 20.04
Results after manual installation

`/home/phd/PINCE/libPINCE/SysUtils.py:253: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if issue_path is "delete":
/home/phd/PINCE/libPINCE/SysUtils.py:257: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if issue_path is "create":
/home/phd/PINCE/libPINCE/GDB_Engine.py:265: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if currentpid is -1 or SysUtils.is_process_valid(currentpid):
/home/phd/PINCE/libPINCE/GDB_Engine.py:401: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if result is -1:
/home/phd/PINCE/libPINCE/GDB_Engine.py:743: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if result is "0" or not result:
/home/phd/PINCE/libPINCE/GDB_Engine.py:745: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if new_result is "0" or not new_result:
Traceback (most recent call last):
  File "PINCE.py", line 32, in <module>
    from libPINCE.libscanmem.scanmem import Scanmem
ModuleNotFoundError: No module named 'libPINCE.libscanmem'
`

**Comment by vikke1234** [comment]
the manual installation guide hasn't been updated apparently, running `install_pince.sh` should make it work

**Comment by korcankaraokcu** [comment]
What made you use the the manual installation? Can you post the errors you've encountered from executing the `install_pince.sh` script?

**Comment by korcankaraokcu** [comment]
Also, I think I'll delete the manual installation part of the readme. It only repeats what `install_pince.sh` does and it's easy to forget updating it. It might be better if people post the errors they've faced from `install_pince.sh`

**Comment by korcankaraokcu** [comment]
I've fixed some of the warnings with https://github.com/korcankaraokcu/PINCE/commit/66b01b1c7c7c45956947475ce632c124460175b2

**Comment by NazonoMito** [comment]
I used `--recursive`, but it still has some error when i run the `PINCE.sh`.
20.04.1-Ubuntu.

`Traceback (most recent call last):`
 ` File "PINCE.py", line 32, in <module>`
  `  from libPINCE.libscanmem.scanmem import Scanmem`
 ` File "/home/xx/PINCE/libPINCE/libscanmem/scanmem.py", line 28, in <module>`
  `  from . import misc`
`  File "/home/xx/PINCE/libPINCE/libscanmem/misc.py", line 24, in <module>`
 `   from gi.repository import Gtk`
 ` File "/usr/lib/python3/dist-packages/gi/importer.py", line 132, in load_module`
   ` raise ImportError('cannot import name %s, `
`ImportError: cannot import name Gtk, introspection typelib not found`

**Comment by korcankaraokcu** [comment]
Can you write down what exactly did you run?
