### ISSUE TITLE
Process Stops as soon as selected

### ISSUE THREAD

**Issue by UltraBlackLinux** [korcankaraokcu/PINCE#89]
Hey, there.
As soon as I select a process and interact with the game, the process freezes and Pince tells me it's stopped - is it just a configuration problem? This problem already exists for years.
Please tell me a solution, this program is the most similar program to cheat engine for linux!

I am running Manjaro KDE with Pince-git r642.78...

Thanks!

**Comment by korcankaraokcu** [comment]
Check if the logs have something like `received signal SIGSEGV`

Also, what's the title of the game? I'd like to reproduce if it's a free game

**Comment by UltraBlackLinux** [comment]
As soon as I am interacting with the game, I get this line `~"2 \"java\" received signal SIGSEGV, Segmentation fault.\n` then the game stops.
I tried to play shattered pixel dungeon, and jff also Mindustry but as expected, pince has no mercy freezing the processes to death xD

**Comment by korcankaraokcu** [comment]
This is a known issue for Java games. Try to open up the gdb console from the top right and execute this command `handle SIGSEGV nostop noprint`

**Comment by UltraBlackLinux** [comment]
Could you please make this automatic?

**Comment by korcankaraokcu** [comment]
This will also suppress an actual segfault signal so I'll need to check it out myself as well. I might give an option for users to disable segfault signals for java processes.

**Comment by D0A1V2I3D** [comment]
tried thes with minecraft "handle SIGSEGV nostop noprint" worked, tysm for making an amazing tool

**Comment by korcankaraokcu** [comment]
> Could you please make this automatic?

https://github.com/korcankaraokcu/PINCE/commit/78b04d0ca25d898f88bd3d32c8574bd402ad6b0b Now you have the option to ignore SIGSEGV with this commit
