### ISSUE TITLE
[AUR] pince won't start, complaining about GTK and freezing (as root) or crashing (as non-root)

### ISSUE THREAD

**Issue by CocaineJohnsson** [korcankaraokcu/PINCE#91]
Output when run as superuser, which it insists I should do by invoking sudo whether I want it or not:

`/usr/share/PINCE/libPINCE/libscanmem/misc.py:24: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
QStandardPaths: runtime directory '/run/user/1000' is not owned by UID 0, but a directory permissions 0700 owned by UID 1000 GID 1000
/usr/share/PINCE/PINCE.py:5022: Warning: cannot register existing type 'GtkWidget'
  app = QApplication(sys.argv)
/usr/share/PINCE/PINCE.py:5022: Warning: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
  app = QApplication(sys.argv)
/usr/share/PINCE/PINCE.py:5022: Warning: cannot register existing type 'GtkBuildable'
  app = QApplication(sys.argv)
/usr/share/PINCE/PINCE.py:5022: Warning: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
  app = QApplication(sys.argv)
/usr/share/PINCE/PINCE.py:5022: Warning: g_once_init_leave: assertion 'result != 0' failed
  app = QApplication(sys.argv)
/usr/share/PINCE/PINCE.py:5022: Warning: g_type_register_static: assertion 'parent_type > 0' failed
  app = QApplication(sys.argv)
`

This takes approximately 23ms of cpu time and then it just sits there on about 8M of ram doing nothing, the README.md and wiki didn't shine a light on it and a cursory web search didn't really reveal anything either, nor did any previous issues (both open and closed).

Output when run as `sudo -u user_name pince`:

`
/usr/share/PINCE/libPINCE/libscanmem/misc.py:24: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
/usr/bin/pince: line 26:  3194 Segmentation fault      sudo -E python3 PINCE.py
`

This is, as the PID implies, from a cold booted system just in case that would have any relevancy (though aside from library version mismatches I doubt that'd have any relevancy)

This is on a relatively minimal arch system running awesomeWM and not much more as the x-server is concerned, invoked from commandline.

**Comment by korcankaraokcu** [comment]
I've recently updated the installation script and tested on arch, it seems to work fine without any issues. If you are still having this issue, refer to #153
