### ISSUE TITLE
I got this error when i tried to launch

### ISSUE THREAD

**Issue by OrangeZt** [korcankaraokcu/PINCE#94]
PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
PINCE.py:5022: Warning: cannot register existing type 'GtkWidget'
  app = QApplication(sys.argv)
PINCE.py:5022: Warning: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
  app = QApplication(sys.argv)
PINCE.py:5022: Warning: cannot register existing type 'GtkBuildable'
  app = QApplication(sys.argv)
PINCE.py:5022: Warning: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
  app = QApplication(sys.argv)
PINCE.py:5022: Warning: g_once_init_leave: assertion 'result != 0' failed
  app = QApplication(sys.argv)
PINCE.py:5022: Warning: g_type_register_static: assertion 'parent_type > 0' failed
  app = QApplication(sys.argv)

**Comment by korcankaraokcu** [comment]
I can't reproduce this on my end, I can only produce the following error on launch:
`PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.`

What's your dist?

**Comment by ManyHatsOfLinux** [comment]
I see the default uid here (1000) Could it be that you are not running as root?

**Comment by YogSottot** [comment]
> QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0

I have the same error on kubuntu 20.04
Fixed  with
```sudo mkdir -p /run/user/0```
```XDG_RUNTIME_DIR=/run/user/0 sudo -E python3 PINCE.py```

**Comment by korcankaraokcu** [comment]
Linking to #153

Continue from there if you are still having issues
